//! The audit event catalog (`spec/telemetry/audit-event-catalog.json`): one
//! adapter per source (provenance format, adapter version, commitment and
//! registration requirements, trace id capability) and one entry per event
//! type with its source, origin, class, resources, results, subject shapes,
//! typed fields and mapping rules. The catalog is the single source for
//! validation, the generated JSON Schema and the Store's `registered_types`.

use std::collections::{BTreeMap, BTreeSet};
use std::sync::OnceLock;

use serde::Deserialize;
use serde_json::{Map, Value};

use crate::codes::Rejection;
use crate::json::parse_bounded;
use crate::kinds::{Kind, MAX_STRING_BYTES, is_event_type};

const EMBEDDED_CATALOG: &str = include_str!("../../../spec/telemetry/audit-event-catalog.json");
const MAX_CATALOG_BYTES: usize = 512 * 1024;
const MAX_CATALOG_DEPTH: usize = 8;

/// The only catalog format version this crate understands.
pub const CATALOG_VERSION: u32 = 1;
/// Source of every Document platform audit event.
pub const DOCUMENT_SOURCE: &str = "urn:knowledge-platform:document-platform";
/// Source of control events generated inside the Audit Store.
pub const AUDIT_STORE_SOURCE: &str = "urn:knowledge-platform:audit-store";
/// Source of control events generated by the audit relay.
pub const AUDIT_RELAY_SOURCE: &str = "urn:knowledge-platform:audit-relay";
/// Prefix reserved for control event types.
pub const CONTROL_TYPE_PREFIX: &str = "audit.";

/// Who may submit an event type: the relay (external sources) or the Store /
/// relay itself (control events, never accepted through the relay path).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Origin {
    Relay,
    Store,
    RelayControl,
}

impl Origin {
    pub const ALL: [Self; 3] = [Self::Relay, Self::Store, Self::RelayControl];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Relay => "relay",
            Self::Store => "store",
            Self::RelayControl => "relay_control",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        Self::ALL
            .into_iter()
            .find(|origin| origin.as_str() == value)
    }
}

/// OA §14 event classes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum EventClass {
    Security,
    PrivilegedOperation,
    ContentLifecycle,
    AccessPolicy,
    DataAccess,
    SearchAccess,
    Configuration,
    SystemAudit,
}

impl EventClass {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Security => "SECURITY",
            Self::PrivilegedOperation => "PRIVILEGED_OPERATION",
            Self::ContentLifecycle => "CONTENT_LIFECYCLE",
            Self::AccessPolicy => "ACCESS_POLICY",
            Self::DataAccess => "DATA_ACCESS",
            Self::SearchAccess => "SEARCH_ACCESS",
            Self::Configuration => "CONFIGURATION",
            Self::SystemAudit => "SYSTEM_AUDIT",
        }
    }
}

/// Resource types an event may name.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Deserialize)]
pub enum ResourceType {
    Document,
    Folder,
    AccessPolicy,
    AuditStore,
}

impl ResourceType {
    pub const ALL: [Self; 4] = [
        Self::Document,
        Self::Folder,
        Self::AccessPolicy,
        Self::AuditStore,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Document => "Document",
            Self::Folder => "Folder",
            Self::AccessPolicy => "AccessPolicy",
            Self::AuditStore => "AuditStore",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|kind| kind.as_str() == value)
    }
}

/// Whether an optional provenance member must, may or must not be present.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Requirement {
    Required,
    Optional,
    Forbidden,
}

/// How one source submits events: its provenance contract.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AdapterSpec {
    pub source: String,
    pub origin: Origin,
    /// `provenance.source_format` of every event of this source.
    pub source_format: String,
    /// `provenance.adapter_version` of every event of this source: the
    /// current projection version (design §7.2). Bumped whenever the
    /// projection output of an existing type changes.
    pub adapter_version: i32,
    /// `provenance.source_commitment`.
    pub commitment: Requirement,
    /// `provenance.registration`.
    pub registration: Requirement,
    /// Whether `correlation.trace_id` may be set. Reserved: only an adapter
    /// with a dedicated W3C trace column may set it.
    pub trace_id: bool,
}

/// Fixed resource id used by `AuditStore` resources.
pub const AUDIT_STORE_RESOURCE_ID: &str = "audit-store";

/// Whether `resource.version_id` must, must not, or may be present.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VersionRequirement {
    Required,
    Forbidden,
    Optional,
}

impl<'de> Deserialize<'de> for VersionRequirement {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        #[derive(Deserialize)]
        #[serde(untagged)]
        enum Repr {
            Flag(bool),
            Word(String),
        }
        match Repr::deserialize(deserializer)? {
            Repr::Flag(true) => Ok(Self::Required),
            Repr::Flag(false) => Ok(Self::Forbidden),
            Repr::Word(word) if word == "optional" => Ok(Self::Optional),
            Repr::Word(_) => Err(serde::de::Error::custom(
                "version_required must be true, false or \"optional\"",
            )),
        }
    }
}

/// How the free-text `reason` of a source row is represented.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReasonPolicy {
    /// The source never records a reason; the payload has no `reason` member.
    Absent,
    /// The source records caller text; only `{provided, utf8_bytes,
    /// text_retained}` reaches the Store.
    CallerText,
}

/// A typed `details` field.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FieldSpec {
    pub kind: Kind,
    /// The closed set of enum kinds (from the entry) and of source kinds
    /// (derived by the loader from the catalog's sources).
    #[serde(default)]
    pub values: Vec<String>,
    /// The producer accepts a client-chosen id here (relay uuid kinds only),
    /// so a nil UUID is the producer-reachable `nil_client_id` instead of
    /// `invalid_field`.
    #[serde(default)]
    pub client_chosen: bool,
}

impl FieldSpec {
    pub fn accepts(&self, value: &Value) -> bool {
        self.kind.accepts(&self.values, value)
    }
}

/// What a bound `details` field must equal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Deserialize)]
pub enum BindingTarget {
    #[serde(rename = "resource.id")]
    ResourceId,
    #[serde(rename = "resource.version_id")]
    ResourceVersionId,
    #[serde(rename = "resource.type")]
    ResourceType,
}

impl BindingTarget {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ResourceId => "resource.id",
            Self::ResourceVersionId => "resource.version_id",
            Self::ResourceType => "resource.type",
        }
    }
}

/// `details[field]` must equal the named resource attribute.
#[derive(Debug, Clone, PartialEq, Eq, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Binding {
    pub field: String,
    pub equals: BindingTarget,
}

/// One part of a subject template.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Segment {
    Literal(String),
    ResourceId,
    ResourceVersionId,
    Detail(String),
}

/// A permitted subject shape, optionally restricted to one resource type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubjectSpec {
    pub template: String,
    pub resource: Option<ResourceType>,
    pub segments: Vec<Segment>,
}

impl SubjectSpec {
    /// Renders the subject for a concrete resource and details object.
    /// Returns `None` when a placeholder cannot be resolved.
    pub fn render(
        &self,
        resource_type: ResourceType,
        resource_id: &str,
        version_id: Option<&str>,
        details: &Map<String, Value>,
    ) -> Option<String> {
        if self.resource.is_some_and(|only| only != resource_type) {
            return None;
        }
        let mut out = String::new();
        for segment in &self.segments {
            match segment {
                Segment::Literal(text) => out.push_str(text),
                Segment::ResourceId => out.push_str(resource_id),
                Segment::ResourceVersionId => out.push_str(version_id?),
                Segment::Detail(name) => out.push_str(details.get(name)?.as_str()?),
            }
        }
        Some(out)
    }
}

/// One catalog entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EventSpec {
    pub event_type: String,
    pub source: String,
    pub origin: Origin,
    pub event_class: EventClass,
    pub resources: Vec<ResourceType>,
    pub version_required: VersionRequirement,
    pub results: Vec<String>,
    pub subjects: Vec<SubjectSpec>,
    /// Source data keys (legacy names), excluding the free-text `reason`.
    pub fields: BTreeMap<String, FieldSpec>,
    pub required: Vec<String>,
    pub reason: ReasonPolicy,
    pub reason_code_field: Option<String>,
    pub service_executor_field: Option<String>,
    pub duplicated_actor_field: Option<String>,
    pub operation_id_field: Option<String>,
    pub publish_operation_id_field: Option<String>,
    pub nil_resource_allowed: bool,
    pub bindings: Vec<Binding>,
    /// Resource types whose `resource.id` the producer lets clients choose
    /// (relay entries only): a nil id is `nil_client_id` there.
    pub client_chosen_resource_ids: Vec<ResourceType>,
    /// Whether `resource.version_id` may be client-chosen (relay entries
    /// with versions only): a nil version id is `nil_client_id` then.
    pub client_chosen_version_id: bool,
}

impl EventSpec {
    /// Whether `name` stays in `details` (it is a field that is neither lifted
    /// into `service_executor` nor dropped as a duplicated actor).
    pub fn is_detail_field(&self, name: &str) -> bool {
        self.fields.contains_key(name)
            && self.service_executor_field.as_deref() != Some(name)
            && self.duplicated_actor_field.as_deref() != Some(name)
    }

    /// Fields that remain in `details`, in name order.
    pub fn detail_fields(&self) -> impl Iterator<Item = (&str, &FieldSpec)> {
        self.fields
            .iter()
            .filter(|(name, _)| self.is_detail_field(name))
            .map(|(name, spec)| (name.as_str(), spec))
    }

    /// Required fields that remain in `details`.
    pub fn detail_required(&self) -> impl Iterator<Item = &str> {
        self.required
            .iter()
            .map(String::as_str)
            .filter(|name| self.is_detail_field(name))
    }

    pub fn allows_resource(&self, resource: ResourceType) -> bool {
        self.resources.contains(&resource)
    }

    pub fn allows_result(&self, result: &str) -> bool {
        self.results.iter().any(|allowed| allowed == result)
    }
}

/// A validated catalog.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Catalog {
    version: u32,
    adapters: Vec<AdapterSpec>,
    events: Vec<EventSpec>,
    index: BTreeMap<String, usize>,
}

/// Why a catalog document was refused. Messages name catalog entries, which
/// are trusted specification content.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum CatalogError {
    #[error("catalog is not valid unique-key JSON ({0})")]
    Json(&'static str),
    #[error("catalog shape is invalid: {0}")]
    Shape(String),
    #[error("catalog version must be {CATALOG_VERSION}")]
    Version,
    #[error("catalog entry {event_type}: {problem}")]
    Entry { event_type: String, problem: String },
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawCatalog {
    version: u32,
    adapters: Vec<AdapterSpec>,
    events: Vec<RawEvent>,
}

#[derive(Deserialize)]
#[serde(untagged)]
enum RawSubject {
    Template(String),
    Scoped(ScopedSubject),
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ScopedSubject {
    template: String,
    resource: ResourceType,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawEvent {
    #[serde(rename = "type")]
    event_type: String,
    source: String,
    origin: Origin,
    event_class: EventClass,
    resources: Vec<ResourceType>,
    version_required: VersionRequirement,
    results: Vec<String>,
    subjects: Vec<RawSubject>,
    fields: BTreeMap<String, FieldSpec>,
    required: Vec<String>,
    reason: ReasonPolicy,
    #[serde(default)]
    reason_code_field: Option<String>,
    #[serde(default)]
    service_executor_field: Option<String>,
    #[serde(default)]
    duplicated_actor_field: Option<String>,
    #[serde(default)]
    operation_id_field: Option<String>,
    #[serde(default)]
    publish_operation_id_field: Option<String>,
    #[serde(default)]
    nil_resource_allowed: bool,
    #[serde(default)]
    bindings: Vec<Binding>,
    #[serde(default)]
    client_chosen_resource_ids: Vec<ResourceType>,
    #[serde(default)]
    client_chosen_version_id: bool,
}

impl Catalog {
    /// The catalog embedded from `spec/telemetry/audit-event-catalog.json`.
    ///
    /// # Panics
    ///
    /// Panics if the embedded specification is invalid; the crate's tests
    /// guarantee it is not.
    pub fn embedded() -> &'static Catalog {
        static CATALOG: OnceLock<Catalog> = OnceLock::new();
        CATALOG.get_or_init(|| {
            Catalog::from_json(EMBEDDED_CATALOG).unwrap_or_else(|error| {
                panic!("embedded audit catalog is invalid: {error}");
            })
        })
    }

    /// The raw embedded catalog text (for reproducibility checks).
    pub fn embedded_text() -> &'static str {
        EMBEDDED_CATALOG
    }

    /// Parses and validates a catalog document.
    pub fn from_json(text: &str) -> Result<Self, CatalogError> {
        let value = parse_bounded(text, MAX_CATALOG_BYTES, MAX_CATALOG_DEPTH)
            .map_err(|rejection| CatalogError::Json(rejection.code.as_str()))?;
        let raw: RawCatalog = serde_json::from_value(value)
            .map_err(|error| CatalogError::Shape(error.to_string()))?;
        if raw.version != CATALOG_VERSION {
            return Err(CatalogError::Version);
        }
        check_adapters(&raw.adapters)?;
        let sources = catalog_sources(&raw.adapters);
        let mut events = Vec::with_capacity(raw.events.len());
        let mut index = BTreeMap::new();
        for raw_event in raw.events {
            let event = check_event(raw_event, &sources)?;
            if !raw
                .adapters
                .iter()
                .any(|a| a.source == event.source && a.origin == event.origin)
            {
                return Err(entry_error(
                    &event.event_type,
                    "no adapter with this source and origin",
                ));
            }
            if index
                .insert(event.event_type.clone(), events.len())
                .is_some()
            {
                return Err(entry_error(&event.event_type, "duplicate type"));
            }
            events.push(event);
        }
        if let Some(unused) = raw
            .adapters
            .iter()
            .find(|a| !events.iter().any(|e| e.source == a.source))
        {
            return Err(CatalogError::Shape(format!(
                "adapter {} has no event types",
                unused.source
            )));
        }
        Ok(Self {
            version: raw.version,
            adapters: raw.adapters,
            events,
            index,
        })
    }

    pub fn version(&self) -> u32 {
        self.version
    }

    /// Entries in catalog order.
    pub fn events(&self) -> &[EventSpec] {
        &self.events
    }

    /// Looks up an entry by event type.
    pub fn get(&self, event_type: &str) -> Option<&EventSpec> {
        self.index.get(event_type).map(|&i| &self.events[i])
    }

    /// Adapters in catalog order.
    pub fn adapters(&self) -> &[AdapterSpec] {
        &self.adapters
    }

    /// The adapter of a source. Every event's source has exactly one.
    pub fn adapter(&self, source: &str) -> Option<&AdapterSpec> {
        self.adapters.iter().find(|a| a.source == source)
    }

    /// `(source, type, adapter_version)` of every relay-origin type, in
    /// catalog order: the rows of the Store's `registered_types` (design
    /// §7.1). Control types are not ingested and are not listed.
    pub fn registered_types(&self) -> Vec<(&str, &str, i32)> {
        self.events
            .iter()
            .filter(|e| e.origin == Origin::Relay)
            .filter_map(|e| {
                self.adapter(&e.source)
                    .map(|a| (e.source.as_str(), e.event_type.as_str(), a.adapter_version))
            })
            .collect()
    }

    /// Validates an envelope value for a submission path against this
    /// catalog (the embedded one is [`crate::validate_envelope`]). The
    /// catalog must be `'static` (embedded or leaked) because rejections name
    /// catalog fields as static strings.
    pub fn validate(
        &'static self,
        value: &Value,
        path: Origin,
    ) -> Result<&'static EventSpec, Rejection> {
        crate::envelope::validate_with(self, value, path)
    }
}

/// The closed set of `source_urn` / `source_list` values: every adapter
/// source plus the two control sources, sorted.
fn catalog_sources(adapters: &[AdapterSpec]) -> Vec<String> {
    let set: BTreeSet<&str> = adapters
        .iter()
        .map(|a| a.source.as_str())
        .chain([AUDIT_STORE_SOURCE, AUDIT_RELAY_SOURCE])
        .collect();
    set.into_iter().map(str::to_owned).collect()
}

fn is_source_format(text: &str) -> bool {
    !text.is_empty()
        && text.len() <= 64
        && text
            .bytes()
            .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
}

fn check_adapters(adapters: &[AdapterSpec]) -> Result<(), CatalogError> {
    let shape = |message: String| Err(CatalogError::Shape(message));
    if adapters.is_empty() {
        return shape("adapters must be non-empty".to_owned());
    }
    if !unique(adapters.iter().map(|a| &a.source))
        || !unique(adapters.iter().map(|a| &a.source_format))
    {
        return shape("adapter sources and source formats must be unique".to_owned());
    }
    for adapter in adapters {
        let source = adapter.source.as_str();
        let source_ok = match adapter.origin {
            Origin::Store => source == AUDIT_STORE_SOURCE,
            Origin::RelayControl => source == AUDIT_RELAY_SOURCE,
            Origin::Relay => {
                source != AUDIT_STORE_SOURCE
                    && source != AUDIT_RELAY_SOURCE
                    && source.starts_with("urn:")
                    && source.len() <= MAX_STRING_BYTES
            }
        };
        if !source_ok {
            return shape(format!("adapter {source}: source does not fit its origin"));
        }
        if !is_source_format(&adapter.source_format) {
            return shape(format!(
                "adapter {source}: source_format must be [a-z0-9-]{{1,64}}"
            ));
        }
        if adapter.adapter_version < 1 {
            return shape(format!(
                "adapter {source}: adapter_version must be at least 1"
            ));
        }
        if adapter.origin != Origin::Relay
            && (adapter.commitment != Requirement::Forbidden
                || adapter.registration != Requirement::Forbidden
                || adapter.trace_id)
        {
            return shape(format!(
                "adapter {source}: control adapters carry no commitment, registration or trace id"
            ));
        }
    }
    Ok(())
}

fn entry_error(event_type: &str, problem: impl Into<String>) -> CatalogError {
    CatalogError::Entry {
        event_type: event_type.to_owned(),
        problem: problem.into(),
    }
}

fn is_token(text: &str) -> bool {
    let mut chars = text.chars();
    chars.next().is_some_and(|c| c.is_ascii_alphabetic())
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn is_enum_value(text: &str) -> bool {
    !text.is_empty()
        && text.len() <= 64
        && text
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

fn unique<T: Ord>(items: impl IntoIterator<Item = T>) -> bool {
    let mut seen = BTreeSet::new();
    items.into_iter().all(|item| seen.insert(item))
}

fn check_event(mut raw: RawEvent, sources: &[String]) -> Result<EventSpec, CatalogError> {
    let t = raw.event_type.as_str();
    let fail = |problem: &str| entry_error(t, problem);
    if !is_event_type(t) {
        return Err(fail("type must be lowercase dotted segments"));
    }
    let control = t.starts_with(CONTROL_TYPE_PREFIX);
    let expected_source = match raw.origin {
        Origin::Store => Some(AUDIT_STORE_SOURCE),
        Origin::RelayControl => Some(AUDIT_RELAY_SOURCE),
        Origin::Relay => None,
    };
    match expected_source {
        Some(source) if raw.source != source || !control => {
            return Err(fail(
                "control origins need an audit.* type and their own source",
            ));
        }
        None if control
            || raw.source == AUDIT_STORE_SOURCE
            || raw.source == AUDIT_RELAY_SOURCE
            || !raw.source.starts_with("urn:")
            || raw.source.len() > MAX_STRING_BYTES =>
        {
            return Err(fail("relay origin needs a non-control type and source"));
        }
        _ => {}
    }
    if raw.resources.is_empty() || !unique(raw.resources.iter()) {
        return Err(fail("resources must be non-empty and unique"));
    }
    if raw.origin == Origin::Relay && raw.resources.contains(&ResourceType::AuditStore) {
        return Err(fail("AuditStore resources are reserved for control events"));
    }
    if raw.results.is_empty()
        || !unique(raw.results.iter())
        || !raw.results.iter().all(|r| is_token(r))
    {
        return Err(fail("results must be non-empty unique tokens"));
    }
    for (name, field) in &raw.fields {
        if !is_token(name) || name == "reason" {
            return Err(fail("field names must be tokens and must not be reason"));
        }
        if raw.origin == Origin::Relay && field.kind.is_control_only() {
            return Err(entry_error(
                t,
                format!(
                    "{name}: {} is reserved for control events",
                    field.kind.as_str()
                ),
            ));
        }
        if field.kind.takes_values() {
            if field.values.is_empty()
                || !unique(field.values.iter())
                || !field.values.iter().all(|v| is_enum_value(v))
            {
                return Err(entry_error(
                    t,
                    format!("{name}: enum values must be a non-empty set of [A-Za-z0-9_-]{{1,64}}"),
                ));
            }
        } else if !field.values.is_empty() {
            return Err(entry_error(
                t,
                format!("{name}: values only apply to enum kinds"),
            ));
        }
        let uuid_kind = matches!(field.kind, Kind::Uuid | Kind::NullableUuid | Kind::UuidList);
        if field.client_chosen && (raw.origin != Origin::Relay || !uuid_kind) {
            return Err(entry_error(
                t,
                format!("{name}: client_chosen applies to uuid kinds of relay entries"),
            ));
        }
    }
    for field in raw.fields.values_mut() {
        if field.kind.derives_values() {
            field.values = sources.to_vec();
        }
    }
    if raw.origin != Origin::Relay
        && (!raw.client_chosen_resource_ids.is_empty() || raw.client_chosen_version_id)
    {
        return Err(fail("control entries have no client-chosen ids"));
    }
    if !unique(raw.client_chosen_resource_ids.iter())
        || raw
            .client_chosen_resource_ids
            .iter()
            .any(|r| *r == ResourceType::AuditStore || !raw.resources.contains(r))
    {
        return Err(fail(
            "client_chosen_resource_ids must be unique resources of the entry",
        ));
    }
    if raw.client_chosen_version_id && raw.version_required == VersionRequirement::Forbidden {
        return Err(fail("client_chosen_version_id needs versions"));
    }
    if !unique(raw.required.iter()) || raw.required.iter().any(|r| !raw.fields.contains_key(r)) {
        return Err(fail("required must be unique and a subset of fields"));
    }
    let field_kind = |name: &Option<String>| -> Option<Option<Kind>> {
        name.as_ref()
            .map(|name| raw.fields.get(name).map(|spec| spec.kind))
    };
    let is_required = |name: &str| raw.required.iter().any(|r| r == name);
    if let Some(kind) = field_kind(&raw.reason_code_field)
        && (kind != Some(Kind::Enum) || !raw.reason_code_field.as_deref().is_some_and(is_required))
    {
        return Err(fail("reason_code_field must be a required enum field"));
    }
    for (name, label) in [
        (&raw.service_executor_field, "service_executor_field"),
        (&raw.duplicated_actor_field, "duplicated_actor_field"),
    ] {
        if field_kind(name).is_some_and(|kind| kind != Some(Kind::Principal)) {
            return Err(entry_error(
                t,
                format!("{label} must name a principal field"),
            ));
        }
    }
    if raw
        .duplicated_actor_field
        .as_deref()
        .is_some_and(|name| !is_required(name))
    {
        return Err(fail("duplicated_actor_field must be required"));
    }
    if raw.service_executor_field.is_some()
        && raw.service_executor_field == raw.duplicated_actor_field
    {
        return Err(fail("service executor and duplicated actor must differ"));
    }
    for (name, label) in [
        (&raw.operation_id_field, "operation_id_field"),
        (
            &raw.publish_operation_id_field,
            "publish_operation_id_field",
        ),
    ] {
        if field_kind(name).is_some_and(|kind| kind != Some(Kind::Uuid)) {
            return Err(entry_error(t, format!("{label} must name a uuid field")));
        }
    }
    if raw.nil_resource_allowed && raw.resources.contains(&ResourceType::AuditStore) {
        return Err(fail("nil resources cannot apply to AuditStore"));
    }
    if raw.reason == ReasonPolicy::CallerText && raw.origin != Origin::Relay {
        return Err(fail("caller_text reasons exist only on relay events"));
    }
    for binding in &raw.bindings {
        let Some(spec) = raw.fields.get(&binding.field) else {
            return Err(fail("binding names an unknown field"));
        };
        let ok = is_required(&binding.field)
            && match binding.equals {
                BindingTarget::ResourceId => {
                    spec.kind == Kind::Uuid
                        && !raw.nil_resource_allowed
                        && !raw.resources.contains(&ResourceType::AuditStore)
                }
                BindingTarget::ResourceVersionId => {
                    spec.kind == Kind::Uuid && raw.version_required == VersionRequirement::Required
                }
                BindingTarget::ResourceType => {
                    spec.kind == Kind::Enum
                        && spec.values.iter().all(|v| {
                            ResourceType::parse(v).is_some_and(|r| raw.resources.contains(&r))
                        })
                }
            };
        if !ok {
            return Err(entry_error(
                t,
                format!(
                    "binding {} -> {} is not resolvable",
                    binding.field,
                    binding.equals.as_str()
                ),
            ));
        }
    }
    if raw.subjects.is_empty() {
        return Err(fail("subjects must be non-empty"));
    }
    let raw_subjects = std::mem::take(&mut raw.subjects);
    let mut subjects = Vec::with_capacity(raw_subjects.len());
    for subject in raw_subjects {
        let (template, resource) = match subject {
            RawSubject::Template(template) => (template, None),
            RawSubject::Scoped(scoped) => (scoped.template, Some(scoped.resource)),
        };
        if resource.is_some_and(|r| !raw.resources.contains(&r)) {
            return Err(fail("subject resource must be one of resources"));
        }
        let applies_to_store = match resource {
            Some(only) => only == ResourceType::AuditStore,
            None => raw.resources.contains(&ResourceType::AuditStore),
        };
        let segments = parse_template(&template, &raw, applies_to_store)
            .map_err(|problem| entry_error(t, problem))?;
        subjects.push(SubjectSpec {
            template,
            resource,
            segments,
        });
    }
    if !unique(subjects.iter().map(|s| (&s.template, s.resource))) {
        return Err(fail("subjects must be unique"));
    }
    for resource in &raw.resources {
        if !subjects
            .iter()
            .any(|s| s.resource.is_none_or(|only| only == *resource))
        {
            return Err(fail("every resource needs a subject shape"));
        }
    }
    Ok(EventSpec {
        event_type: raw.event_type,
        source: raw.source,
        origin: raw.origin,
        event_class: raw.event_class,
        resources: raw.resources,
        version_required: raw.version_required,
        results: raw.results,
        subjects,
        fields: raw.fields,
        required: raw.required,
        reason: raw.reason,
        reason_code_field: raw.reason_code_field,
        service_executor_field: raw.service_executor_field,
        duplicated_actor_field: raw.duplicated_actor_field,
        operation_id_field: raw.operation_id_field,
        publish_operation_id_field: raw.publish_operation_id_field,
        nil_resource_allowed: raw.nil_resource_allowed,
        bindings: raw.bindings,
        client_chosen_resource_ids: raw.client_chosen_resource_ids,
        client_chosen_version_id: raw.client_chosen_version_id,
    })
}

/// Parses a subject template. `applies_to_store` is true when the subject
/// can render an `AuditStore` resource: `{resource.id}` is refused there,
/// because the id is the literal `audit-store` while the generated schema
/// renders every id placeholder as a UUID.
fn parse_template(
    template: &str,
    raw: &RawEvent,
    applies_to_store: bool,
) -> Result<Vec<Segment>, String> {
    if template.is_empty() || template.len() > 256 {
        return Err("subject template must be 1..=256 bytes".to_owned());
    }
    let mut segments = Vec::new();
    let mut rest = template;
    while !rest.is_empty() {
        if let Some(after) = rest.strip_prefix('{') {
            let end = after
                .find('}')
                .ok_or_else(|| format!("unterminated placeholder in {template}"))?;
            let name = &after[..end];
            let segment = match name {
                "resource.id" if applies_to_store => {
                    return Err(format!(
                        "{template}: {{resource.id}} cannot render the AuditStore resource"
                    ));
                }
                "resource.id" => Segment::ResourceId,
                "resource.version_id" => {
                    if raw.version_required == VersionRequirement::Forbidden {
                        return Err(format!("{template}: version placeholder without versions"));
                    }
                    Segment::ResourceVersionId
                }
                other => {
                    let field = other
                        .strip_prefix("details.")
                        .ok_or_else(|| format!("{template}: unknown placeholder {other}"))?;
                    let resolvable = raw.fields.get(field).is_some_and(|f| f.kind == Kind::Uuid)
                        && raw.required.iter().any(|r| r == field)
                        && raw.service_executor_field.as_deref() != Some(field)
                        && raw.duplicated_actor_field.as_deref() != Some(field);
                    if !resolvable {
                        return Err(format!("{template}: {field} must be a required uuid field"));
                    }
                    Segment::Detail(field.to_owned())
                }
            };
            segments.push(segment);
            rest = &after[end + 1..];
        } else {
            let end = rest.find('{').unwrap_or(rest.len());
            let literal = &rest[..end];
            if !literal.chars().all(|c| {
                c.is_ascii_lowercase() || c.is_ascii_digit() || matches!(c, '/' | '-' | '_' | '.')
            }) {
                return Err(format!(
                    "{template}: literal text must be lowercase path characters"
                ));
            }
            segments.push(Segment::Literal(literal.to_owned()));
            rest = &rest[end..];
        }
    }
    Ok(segments)
}
