export { documentApi } from '../api/document-api';
export type {
  CreateDocumentResult,
  CommandsWithdrawVersion,
  CommandsEndPublication,
  WithdrawResult,
  EndPublicationResult,
  AccessPolicyRead,
  CommandsPolicyExplicit,
  CommandsPolicyInherit,
  DocumentDetail,
  DocumentList,
  DocumentRevisionPage,
  DocumentRevisionSummary,
  DisplayFragment,
  DiffDisplayProjection,
  FileList,
  Folder,
  FolderChildren,
  FolderDetail,
  History,
  PolicyGrantInput,
  RevisionComparisonResponse,
  SourceLocator,
  Version,
  VersionDetail,
  VersionList,
} from '@knowledge-platform/document-api-client';
