import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { createServer as httpServer } from 'node:http';
import { Client } from '@modelcontextprotocol/client';
import { InMemoryTransport } from '@modelcontextprotocol/server';
const require=createRequire(import.meta.url);
const adapter=require('../dist/adapter.cjs');
const id='018f1234-1234-7234-8234-123456789abc';
const agent={principal:{identityProvider:'poc',principalId:'poc-agent'},invocationKind:'agent',presentation:{},expiresAt:'2030-01-01T00:00:00Z'};
async function backend(t,handle){const server=httpServer(handle);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{server.closeAllConnections();server.close();});return `http://127.0.0.1:${server.address().port}/`;}
function json(res,value,status=200){res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(value));}
async function connect(t,url){const api=adapter.createDocumentClient(adapter.loadConfig({KP_DOCUMENT_API_BASE_URL:url}));await adapter.verifyAgentSession(api);const server=adapter.createServer(api);const client=new Client({name:'test',version:'0.0.0'});const [a,b]=InMemoryTransport.createLinkedPair();await server.connect(a);await client.connect(b);t.after(async()=>{await client.close();await server.close();});return client;}
test('configuration is frozen, valid and excludes embedded secrets/fragments',()=>{assert.equal(typeof adapter.loadConfig,'function');const c=adapter.loadConfig({});assert.equal(c.apiBaseUrl,'http://127.0.0.1:8081/');assert.ok(Object.isFrozen(c));for(const url of ['ftp://localhost/','http://a:b@localhost/','http://localhost/#fragment','bad'])assert.throws(()=>adapter.loadConfig({KP_DOCUMENT_API_BASE_URL:url}));});
test('human and redirected session are rejected',async t=>{for(const mode of ['human','redirect']){const url=await backend(t,(req,res)=>mode==='human'?json(res,{...agent,invocationKind:'human_interactive',principal:{identityProvider:'poc',principalId:'poc-human'}}):(res.writeHead(302,{location:'http://127.0.0.1:1/'}),res.end()));await assert.rejects(adapter.verifyAgentSession(adapter.createDocumentClient(adapter.loadConfig({KP_DOCUMENT_API_BASE_URL:url}))));}});
const cases=[
 ['document_get_root',{},'GET','/v1/folders/root'],
 ['document_list_folder',{folderId:id,pageSize:200,cursor:'opaque+=cursor'},'GET',`/v1/folders/${id}/children`],
 ['document_list',{view:'published',folderId:id,includeDescendants:true,pageSize:200},'GET','/v1/documents'],
 ['document_get',{documentId:id,view:'published'},'GET',`/v1/documents/${id}`],
 ['document_list_revisions',{documentId:id,pageSize:200},'GET',`/v1/documents/${id}/revisions`],
 ['document_get_history',{documentId:id,cursor:'opaque'},'GET',`/v1/documents/${id}/history`],
 ['document_compare_versions',{documentId:id,baseVersionId:id,targetVersionId:id,profile:'document-diff-v0',projection:'display',pageSize:100,cursor:''},'POST',`/v1/documents/${id}/comparisons`],
 ['document_compare_revisions',{documentId:id,baseRevisionId:id,targetRevisionId:id,projection:'diff'},'POST',`/v1/documents/${id}/revision-comparisons`],
 ['document_list_files',{documentId:id,versionId:id,purpose:'history'},'GET',`/v1/documents/${id}/versions/${id}/files`],
];
test('exact nine tools route one generated operation and preserve response semantics',async t=>{const seen=[];const value={items:[],nextCursor:'opaque',verdict:'Unknown',coverage:'Partial',truncated:true,metadata:'unavailable_legacy'};const url=await backend(t,(req,res)=>{if(req.url==='/v1/session')return json(res,agent);let body='';req.on('data',x=>body+=x);req.on('end',()=>{seen.push({method:req.method,url:new URL(req.url,'http://test'),body:body?JSON.parse(body):undefined});json(res,value);});});const client=await connect(t,url);const catalog=await client.listTools();assert.deepEqual(catalog.tools.map(x=>x.name).sort(),cases.map(x=>x[0]).sort());for(const [name,args,method,path]of cases){const result=await client.callTool({name,arguments:args});assert.deepEqual(result.structuredContent,value);assert.deepEqual(JSON.parse(result.content[0].text),value);assert.equal(seen.at(-1).method,method);assert.equal(seen.at(-1).url.pathname,path);const {documentId,folderId,versionId,...rest}=args;const expected=name==='document_list'?args:rest;if(method==='POST')assert.deepEqual(seen.at(-1).body,expected);else for(const [key,val]of Object.entries(expected))assert.equal(seen.at(-1).url.searchParams.get(key),String(val));}assert.equal(seen.length,9);});
test('invalid arguments never reach API; no identity or destination overrides',async t=>{let calls=0;const url=await backend(t,(req,res)=>{if(req.url==='/v1/session')return json(res,agent);calls++;json(res,{});});const client=await connect(t,url);for(const [name,args]of [['document_list',{view:'published',pageSize:201}],['document_get',{documentId:id,view:'published',identity:'poc-human'}],['document_get_root',{apiBaseUrl:'http://evil'}],['document_compare_revisions',{documentId:id,baseRevisionId:id,targetRevisionId:id,projection:'diff',pageSize:101}]]){try{const r=await client.callTool({name,arguments:args});assert.equal(r.isError,true);}catch(e){assert.match(e.message,/invalid|validation|argument/i);}}assert.equal(calls,0);});
test('API errors preserve stable code/status/trace and redact arbitrary diagnostics',async t=>{let status=403;const url=await backend(t,(req,res)=>req.url==='/v1/session'?json(res,agent):json(res,{type:'about:blank',title:'unsafe sensitive text',status,code:'FORBIDDEN',traceId:'trace-123',retryable:false,detail:'secret'},status));const client=await connect(t,url);for(status of [403,404,409,504]){const r=await client.callTool({name:'document_get',arguments:{documentId:id,view:'published'}});assert.equal(r.isError,true);const v=JSON.parse(r.content[0].text);assert.equal(v.status,status);assert.equal(v.code,'FORBIDDEN');assert.equal(v.traceId,'trace-123');assert.doesNotMatch(JSON.stringify(r),/secret|unsafe sensitive/);}});
test('RFC3339 lowercase and leap-second query inputs reach API unchanged',async t=>{const seen=[];const url=await backend(t,(req,res)=>{if(req.url==='/v1/session')return json(res,agent);seen.push(new URL(req.url,'http://test').searchParams.get('createdFrom'));json(res,{items:[],nextCursor:null});});const client=await connect(t,url);for(const createdFrom of ['2026-10-01t00:00:00z','2016-12-31T23:59:60Z']){const r=await client.callTool({name:'document_list',arguments:{view:'published',createdFrom}});assert.notEqual(r.isError,true);}assert.deepEqual(seen,['2026-10-01t00:00:00z','2016-12-31T23:59:60Z']);});
test('UUID format is not narrowed to particular version or variant bits',async t=>{let called=false;const url=await backend(t,(req,res)=>{if(req.url==='/v1/session')return json(res,agent);called=true;json(res,{});});const client=await connect(t,url);const r=await client.callTool({name:'document_get',arguments:{documentId:'018f1234-1234-f234-0234-123456789abc',view:'published'}});assert.notEqual(r.isError,true);assert.ok(called);});
test('all diff verdict/coverage combinations and truncation are unmodified',async t=>{let value;const url=await backend(t,(req,res)=>json(res,req.url==='/v1/session'?agent:value));const client=await connect(t,url);for(const verdict of ['Same','Different','Unknown'])for(const coverage of ['Full','Partial','None']){value={verdict,coverage,truncated:true,metadataSnapshotStatus:'unavailableLegacy',metadataSnapshot:null};const result=await client.callTool({name:'document_compare_versions',arguments:{documentId:id,baseVersionId:id,targetVersionId:id,profile:'document-diff-v0',projection:'diff'}});assert.deepEqual(result.structuredContent,value);}});
test('transport failures and upstream HTML are generic; comparison POST is never retried',async t=>{let calls=0;const url=await backend(t,(req,res)=>{if(req.url==='/v1/session')return json(res,agent);calls++;res.writeHead(502,{'content-type':'text/html'});res.end('<html>secret upstream detail</html>');});const client=await connect(t,url);const r=await client.callTool({name:'document_compare_versions',arguments:{documentId:id,baseVersionId:id,targetVersionId:id,profile:'document-diff-v0',projection:'diff'}});assert.equal(r.isError,true);assert.doesNotMatch(JSON.stringify(r),/secret|html/);assert.equal(calls,1);});
test('RFC9457 trace correlation is preserved without inventing a format restriction',async t=>{const url=await backend(t,(req,res)=>req.url==='/v1/session'?json(res,agent):json(res,{type:'about:blank',title:'Denied',status:403,code:'FORBIDDEN',traceId:'trace:123.456',retryable:false},403));const client=await connect(t,url);const r=await client.callTool({name:'document_get',arguments:{documentId:id,view:'published'}});assert.equal(r.structuredContent.traceId,'trace:123.456');});
