import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {Client} from '@modelcontextprotocol/client';
import {StdioClientTransport} from '@modelcontextprotocol/client/stdio';
const main=new URL('../dist/main.cjs',import.meta.url).pathname;
const session={principal:{identityProvider:'poc',principalId:'poc-agent'},invocationKind:'agent'};
async function backend(t,handle){const s=createServer(handle);await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>{s.closeAllConnections();s.close();});return `http://127.0.0.1:${s.address().port}/`;}
function json(res,data){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(data));}
async function connect(t,url){const transport=new StdioClientTransport({command:process.execPath,args:[main],env:{KP_DOCUMENT_API_BASE_URL:url},stderr:'pipe'});let stderr='';transport.stderr.on('data',x=>stderr+=x);const client=new Client({name:'stdio-tests',version:'0.0.0'});await client.connect(transport);t.after(()=>client.close());return {client,transport,stderr:()=>stderr};}
test('real subprocess stdio initialize/list/call/close, protocol-only stdout',async t=>{const url=await backend(t,(req,res)=>json(res,req.url==='/v1/session'?session:{folderId:'synthetic-root'}));const {client,stderr}=await connect(t,url);assert.equal((await client.listTools()).tools.length,9);const result=await client.callTool({name:'document_get_root',arguments:{}});assert.equal(result.structuredContent.folderId,'synthetic-root');assert.equal(JSON.parse(result.content[0].text).folderId,'synthetic-root');await client.close();assert.equal(stderr(),'');});
test('actual protocol cancellation aborts accepted upstream request',async t=>{let accepted;const requestAccepted=new Promise(r=>accepted=r);let closed;const requestClosed=new Promise(r=>closed=r);const url=await backend(t,(req,res)=>{if(req.url==='/v1/session')return json(res,session);res.on('close',closed);accepted();});const {client}=await connect(t,url);const controller=new AbortController();const call=client.callTool({name:'document_get_root',arguments:{}},{signal:controller.signal});await requestAccepted;controller.abort();await assert.rejects(call);await Promise.race([requestClosed,new Promise((_,reject)=>setTimeout(()=>reject(new Error('HTTP request was not aborted')),3000).unref())]);});
test('tool deadline aborts upstream that accepts but never responds', {timeout:40000},async t=>{const url=await backend(t,(req,res)=>{if(req.url==='/v1/session')json(res,session);});const {client}=await connect(t,url);const start=Date.now();const result=await client.callTool({name:'document_get_root',arguments:{}},{timeout:39000});assert.equal(result.isError,true);assert.ok(Date.now()-start>=34000);assert.ok(Date.now()-start<39000);});
test('preflight deadline bounds silent upstream and emits no raw endpoint', {timeout:40000},async t=>{const url=await backend(t,()=>{});const child=spawn(process.execPath,[main],{env:{KP_DOCUMENT_API_BASE_URL:url},stdio:['pipe','pipe','pipe']});let out='',err='';child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);t.after(()=>child.kill());const start=Date.now();const code=await new Promise(r=>child.on('exit',r));assert.equal(code,1);assert.equal(out,'');assert.match(err,/startup failed/);assert.ok(!err.includes(url));assert.ok(Date.now()-start<39000);});
test('EOF terminates initialized stdio cleanly',async t=>{const url=await backend(t,(req,res)=>json(res,session));const child=spawn(process.execPath,[main],{env:{KP_DOCUMENT_API_BASE_URL:url},stdio:['pipe','pipe','pipe']});t.after(()=>child.kill());child.stdin.end();assert.equal(await new Promise(r=>child.on('exit',r)),0);});
test('EOF during hung preflight promptly aborts startup HTTP', {timeout:6000},async t=>{let accepted;const requestAccepted=new Promise(r=>accepted=r);const url=await backend(t,()=>accepted());const child=spawn(process.execPath,[main],{env:{KP_DOCUMENT_API_BASE_URL:url},stdio:['pipe','pipe','pipe']});t.after(()=>child.kill());await requestAccepted;const exited=new Promise(r=>child.on('exit',r));child.stdin.end();await Promise.race([exited,new Promise((_,reject)=>setTimeout(()=>reject(new Error('preflight ignored EOF')),2000).unref())]);});
test('human profile startup exits before exposing tools and redacts endpoint',async t=>{const url=await backend(t,(req,res)=>json(res,{...session,principal:{identityProvider:'poc',principalId:'poc-human'},invocationKind:'human_interactive'}));const child=spawn(process.execPath,[main],{env:{KP_DOCUMENT_API_BASE_URL:url},stdio:['pipe','pipe','pipe']});t.after(()=>child.kill());let out='',err='';child.stdout.on('data',x=>out+=x);child.stderr.on('data',x=>err+=x);assert.equal(await new Promise(r=>child.on('exit',r)),1);assert.equal(out,'');assert.match(err,/startup failed/);assert.ok(!err.includes(url));});
