import { folderAccessPolicyOperations } from '../src/application/document-folder-access-policy';
import { folderMoveOperations } from '../src/application/document-folder-move';
import { documentMoveOperations } from '../src/application/document-move';
import { QueryClient } from '@tanstack/react-query';
import type { AccessPolicyRead, CommandsPolicyExplicit, DocumentDetail, MutationResult } from '@knowledge-platform/document-api-client';
import { documentAccessPolicyOperations, sendDocumentAccessPolicyOperation, policyChanged, policyRevisionError, validateDocumentPolicy, documentPolicySnapshotEqual } from '../src/application/document-access-policy';
import { refreshFolderMoveReads } from '../src/application/document-folder-move';
const context = { documentId: 'target', title: '資料', view: 'published' as const };
const grant = { subjectKind: 'group' as const, identityProvider: 'issuer', subjectId: 'subject', actions: ['read', 'administer'] as ('read' | 'administer')[] };
const request: CommandsPolicyExplicit = { operationId: 'operation', expectedPolicyRevision: 8, mode: 'explicit', grants: [grant], reason: '理由' };
const policy: AccessPolicyRead = { target: { kind: 'document', id: 'target' }, bindingMode: 'inherit', policyId: null, policyRevision: 8, effectivePolicyId: 'policy', effectiveSource: { kind: 'folder', id: 'parent' }, effectiveGrants: [{ ...grant, presentation: { ref: { kind: 'group', provider: 'issuer', subjectId: 'subject' }, displayName: null, secondaryText: null, resolution: 'unavailable' } }] };
const result: MutationResult = { operationId: 'operation', resourceId: 'target', resultingRevision: 9, changed: true, occurredAt: '2026-10-07T00:00:00Z' };
const problem = (code: string, status: number) => ({ type: 'about:blank', title: 'Synthetic', code, status, traceId: 'synthetic', retryable: false });
const stores: ReturnType<typeof documentAccessPolicyOperations>[] = [];
afterEach(() => stores.splice(0).forEach(store => { const op = store.get(); if (op) { store.put({ ...op, status: 'succeeded' }); store.clearSettled(store.get()!); } }));
function harness() { const owner = {}; const store = documentAccessPolicyOperations(owner); stores.push(store); const send = jest.fn().mockResolvedValue(result); const invalidate = jest.fn().mockResolvedValue(undefined); return { owner, store, send, invalidate, run: (body = request) => sendDocumentAccessPolicyOperation({ store, targetDocumentId: 'target', context, request: body, baseline: policy, send, invalidate }) }; }
test('deep固定要求は呼出元grant/actions変更を防ぎ同一ownerで保持し別ownerを隔離する', async () => {
  const h = harness(); const body = JSON.parse(JSON.stringify(request)) as CommandsPolicyExplicit; h.send.mockRejectedValueOnce(new Error('lost')); await h.run(body); const saved = h.store.get()!;
  body.grants[0]!.actions.pop(); body.grants[0]!.subjectId = 'changed'; body.reason = 'changed';
  expect(saved.request).toEqual(request); expect(Object.isFrozen(saved.request)).toBe(true); if (saved.request.mode === 'explicit') { expect(Object.isFrozen(saved.request.grants)).toBe(true); expect(Object.isFrozen(saved.request.grants[0])).toBe(true); expect(Object.isFrozen(saved.request.grants[0]!.actions)).toBe(true); }
  expect(documentAccessPolicyOperations(h.owner)).toBe(h.store); expect(documentAccessPolicyOperations({}).get()).toBeUndefined(); expect(h.store.clearSettled(saved)).toBe(false);
  await sendDocumentAccessPolicyOperation({ store: h.store, targetDocumentId: 'other', context: { ...context, documentId: 'other' }, request: { ...request, operationId: 'new' }, baseline: policy, send: h.send, invalidate: h.invalidate });
  expect(h.send.mock.calls[1]).toEqual(['target', saved.request]); expect(h.send.mock.calls[1]![1]).toBe(saved.request);
});
test('二重送信とpending消去は不可', async () => { const h = harness(); let resolve!: (v: MutationResult) => void; h.send.mockReturnValue(new Promise<MutationResult>(r => { resolve = r; })); const run = h.run(); expect(h.store.clearSettled(h.store.get()!)).toBe(false); await h.run(); expect(h.send).toHaveBeenCalledTimes(1); resolve(result); await run; expect(h.store.get()?.status).toBe('succeeded'); });
test.each([['FORBIDDEN', 403], ['REVISION_CONFLICT', 409], ['OPERATION_CONFLICT', 409], ['DOCUMENT_NOT_FOUND', 404], ['VALIDATION_FAILED', 422]])('初回%sは拒否、UNKNOWN後同応答は未確定を保持', async (code, status) => { const h = harness(); h.send.mockRejectedValueOnce(problem(code as string, status as number)); await h.run(); expect(h.store.get()?.status).toBe('rejected'); h.store.clearSettled(h.store.get()!); h.send.mockRejectedValueOnce(new Error('lost')); await h.run(); const body = h.store.get()!.request; h.send.mockRejectedValueOnce(problem(code as string, status as number)); await h.run(); expect(h.store.get()?.status).toBe('unknown'); expect(h.store.get()!.request).toBe(body); });
test.each([{ operationId: 'other' }, { resourceId: 'other' }, { changed: false }, { resultingRevision: 8 }, { resultingRevision: 9.5 }, { occurredAt: '2026-02-30T00:00:00Z' }, { occurredAt: '2026-10-07' }, null])('不正receipt %pはUNKNOWN', async patch => { const h = harness(); h.send.mockResolvedValue(patch === null ? null : { ...result, ...patch }); await h.run(); expect(h.store.get()?.status).toBe('unknown'); expect(h.invalidate).not.toHaveBeenCalled(); });
test('成功receipt後current read拒否をmutation失敗へ戻さない', async () => { const h = harness(); h.invalidate.mockRejectedValue(problem('FORBIDDEN', 403)); await h.run(); expect(h.store.get()).toMatchObject({ status: 'succeeded', result, refresh: 'failed' }); });
test('modeとgrant集合の同値を正規化しpresentationと行/action順をno-opに含めない', () => { const baseline = { ...policy, bindingMode: 'explicit' as const }; expect(policyChanged(baseline, { ...request, grants: [{ ...grant, actions: ['administer', 'read'] }] })).toBe(false); expect(policyChanged(policy, request)).toBe(true); expect(policyChanged(policy, { operationId: 'o', mode: 'inherit', expectedPolicyRevision: 8, reason: 'r' })).toBe(false); });
test.each([-1, 0.5, NaN, Infinity, Number.MAX_SAFE_INTEGER])('不正next policyRevision %pを送信しない', async revision => { const h = harness(); await expect(h.run({ ...request, expectedPolicyRevision: revision })).rejects.toThrow(/revision/); expect(h.send).not.toHaveBeenCalled(); });
test('no-opのMAX safe revisionはそのままreceipt照合できる', async () => { expect(policyRevisionError(Number.MAX_SAFE_INTEGER, false)).toBeNull(); const h = harness(); h.send.mockResolvedValue({ ...result, changed: false, resultingRevision: Number.MAX_SAFE_INTEGER }); await sendDocumentAccessPolicyOperation({ store: h.store, context, targetDocumentId: 'target', request: { ...request, expectedPolicyRevision: Number.MAX_SAFE_INTEGER }, baseline: { ...policy, bindingMode: 'explicit' }, send: h.send, invalidate: h.invalidate }); expect(h.store.get()?.status).toBe('succeeded'); });
test('Folder global resetでpolicy読取だけ消去しUNKNOWNをGCから独立して保持', async () => { const client = new QueryClient(); const store = documentAccessPolicyOperations(client); stores.push(store); const h = harness(); h.send.mockRejectedValue(new Error('lost')); await sendDocumentAccessPolicyOperation({ store, context, targetDocumentId: 'target', request, baseline: policy, send: h.send, invalidate: h.invalidate }); const saved = store.get(); client.setQueryData(['document-access-policy', 'target'], policy); await refreshFolderMoveReads(client); expect(client.getQueryData(['document-access-policy', 'target'])).toBeUndefined(); client.clear(); expect(documentAccessPolicyOperations(client).get()).toBe(saved); });
test('read検証は正確targetと5権限と三つ組を保持する', () => { expect(validateDocumentPolicy(policy, 'target')).toBe(true); expect(validateDocumentPolicy({ ...policy, target: { kind: 'folder', id: 'target' } }, 'target')).toBe(false); expect(validateDocumentPolicy({ ...policy, effectiveGrants: [{ ...policy.effectiveGrants[0]!, identityProvider: ' ' }] }, 'target')).toBe(false); });
test('fresh snapshotは同revisionの継承元/grants/文書移動を検知する', () => { const document = { documentId: 'target', title: '資料', revision: 2, folderId: 'parent', capabilities: { manageAccess: { status: 'available' } } } as DocumentDetail; const baseline = { document, policy }; expect(documentPolicySnapshotEqual(baseline, { document, policy: { ...policy, effectiveSource: { kind: 'folder', id: 'other' } } })).toBe(false); expect(documentPolicySnapshotEqual(baseline, { document: { ...document, folderId: 'other' }, policy })).toBe(false); });
test('Unicode照合で似た別subject IDもexact三つ組で集合比較し行順をno-opへ含めない', () => {
  const rows = ['é', 'e\u0301'].map(subjectId => ({ ...policy.effectiveGrants[0]!, subjectId }));
  expect(rows[0]!.subjectId).not.toBe(rows[1]!.subjectId);
  expect(policyChanged({ ...policy, bindingMode: 'explicit', effectiveGrants: rows }, { ...request, grants: [...rows].reverse() })).toBe(false);
});


test.each(['pending', 'unknown', 'rejected', 'succeeded'] as const)('Document ACL成功の同期read失効で他%s要求/Blob/Organization選択は保持する', async status => {
  const client = new QueryClient(); const store = documentAccessPolicyOperations(client); stores.push(store);
  const blob = new Blob(['fixed bytes']); const saved = { status, intent: Object.freeze({ body: Object.freeze({ operationId: 'other' }), files: new Map([['file', blob]]) }) };
  const operationKeys = [['document-working-operation', 'doc'], ['document-schedule-cancel', 'doc', 'version'], ['document-lifecycle-operation', 'doc']]; operationKeys.forEach(key => client.setQueryData(key, saved));
  const read = { title: 'old read' }; const readKeys = [['document', 'doc'], ['documents'], ['document-access-policy', 'target'], ['folder-access-policy', 'folder'], ['document-version-files', 'doc'], ['revision-comparison', 'doc'], ['organization', 'principal', 'assignment', 'document-context', 'doc']]; readKeys.forEach(key => client.setQueryData(key, read));
  const selection = ['organization', 'principal', 'assignment', 'tasks', 'context']; client.setQueryData(selection, read);
  const folderContext = { kind: 'selected' as const, folderId: 'folder', sourceParentId: 'root', name: 'folder', pageLimit: 1 };
  const folderPolicy = folderAccessPolicyOperations(client); folderPolicy.put({ targetFolderId: 'folder', context: folderContext, request, status: 'unknown', expectedChanged: true });
  const folderMove = folderMoveOperations(client); folderMove.put({ targetFolderId: 'folder', context: folderContext, currentName: 'folder', request: { operationId: 'move', expectedFolderRevision: 1, fromParentId: 'root', toParentId: 'other', reason: '理由' }, destination: { kind: 'root', folderId: 'other', name: 'root' }, status: 'unknown', expectedChanged: true });
  const documentMove = documentMoveOperations(client); documentMove.put({ targetDocumentId: 'doc', context: { documentId: 'doc', title: 'doc', view: 'published', folderId: 'root', folderName: 'root' }, request: { operationId: 'move-document', expectedDocumentRevision: 1, fromFolderId: 'root', toFolderId: 'other', reason: '理由' }, destination: { kind: 'root', folderId: 'other', name: 'root' }, status: 'unknown', expectedChanged: true });
  const snapshots = [folderPolicy.get(), folderMove.get(), documentMove.get()];
  await sendDocumentAccessPolicyOperation({ store, targetDocumentId: 'target', context, request, baseline: policy, send: async () => result, invalidate: () => { const refresh = refreshFolderMoveReads(client); readKeys.forEach(key => expect(client.getQueryState(key)?.isInvalidated).toBe(true)); return refresh; } });
  expect(store.get()?.status).toBe('succeeded'); readKeys.forEach(key => expect(client.getQueryData(key)).toBeUndefined()); operationKeys.forEach(key => expect(client.getQueryData(key)).toBe(saved)); expect(saved.intent.files.get('file')).toBe(blob); expect(client.getQueryData(selection)).toBe(read);
  expect([folderPolicy.get(), folderMove.get(), documentMove.get()]).toEqual(snapshots);
  [folderPolicy, folderMove, documentMove].forEach((other, index) => { expect(other.get()).toBe(snapshots[index]); other.put({ ...other.get()!, status: 'succeeded' } as never); other.clearSettled(other.get()! as never); }); client.clear();
});
