import { QueryClient } from '@tanstack/react-query';
import type { AccessPolicyRead, CommandsPolicyExplicit, FolderDetail, MutationResult } from '@knowledge-platform/document-api-client';
import { folderAccessPolicyOperations, sendFolderAccessPolicyOperation, policyChanged, policyRevisionError, validateFolderPolicy, policySnapshotEqual } from '../src/application/document-folder-access-policy';
import { refreshFolderMoveReads } from '../src/application/document-folder-move';
const context = { kind: 'selected' as const, folderId: 'target', sourceParentId: 'parent', pageLimit: 2, name: '資料' };
const grant = { subjectKind: 'group' as const, identityProvider: 'issuer', subjectId: 'subject', actions: ['read', 'administer'] as ('read' | 'administer')[] };
const request: CommandsPolicyExplicit = { operationId: 'operation', expectedPolicyRevision: 8, mode: 'explicit', grants: [grant], reason: '理由' };
const policy: AccessPolicyRead = { target: { kind: 'folder', id: 'target' }, bindingMode: 'inherit', policyId: null, policyRevision: 8, effectivePolicyId: 'policy', effectiveSource: { kind: 'folder', id: 'parent' }, effectiveGrants: [{ ...grant, presentation: { ref: { kind: 'group', provider: 'issuer', subjectId: 'subject' }, displayName: null, secondaryText: null, resolution: 'unavailable' } }] };
const result: MutationResult = { operationId: 'operation', resourceId: 'target', resultingRevision: 9, changed: true, occurredAt: '2026-10-07T00:00:00Z' };
const problem = (code: string, status: number) => ({ type: 'about:blank', title: 'Synthetic', code, status, traceId: 'synthetic', retryable: false });
const stores: ReturnType<typeof folderAccessPolicyOperations>[] = [];
afterEach(() => stores.splice(0).forEach(store => { const op = store.get(); if (op) { store.put({ ...op, status: 'succeeded' }); store.clearSettled(store.get()!); } }));
function harness() { const owner = {}; const store = folderAccessPolicyOperations(owner); stores.push(store); const send = jest.fn().mockResolvedValue(result); const invalidate = jest.fn().mockResolvedValue(undefined); return { owner, store, send, invalidate, run: (body = request) => sendFolderAccessPolicyOperation({ store, targetFolderId: 'target', context, request: body, baseline: policy, send, invalidate }) }; }
test('deep固定要求は呼出元grant/actions変更を防ぎ同一ownerで保持し別ownerを隔離する', async () => {
  const h = harness(); const body = JSON.parse(JSON.stringify(request)) as CommandsPolicyExplicit; h.send.mockRejectedValueOnce(new Error('lost')); await h.run(body); const saved = h.store.get()!;
  body.grants[0]!.actions.pop(); body.grants[0]!.subjectId = 'changed'; body.reason = 'changed';
  expect(saved.request).toEqual(request); expect(Object.isFrozen(saved.request)).toBe(true); if (saved.request.mode === 'explicit') { expect(Object.isFrozen(saved.request.grants)).toBe(true); expect(Object.isFrozen(saved.request.grants[0])).toBe(true); expect(Object.isFrozen(saved.request.grants[0]!.actions)).toBe(true); }
  expect(folderAccessPolicyOperations(h.owner)).toBe(h.store); expect(folderAccessPolicyOperations({}).get()).toBeUndefined(); expect(h.store.clearSettled(saved)).toBe(false);
  await sendFolderAccessPolicyOperation({ store: h.store, targetFolderId: 'other', context: { ...context, folderId: 'other' }, request: { ...request, operationId: 'new' }, baseline: policy, send: h.send, invalidate: h.invalidate });
  expect(h.send.mock.calls[1]).toEqual(['target', saved.request]); expect(h.send.mock.calls[1]![1]).toBe(saved.request);
});
test('二重送信とpending消去は不可', async () => { const h = harness(); let resolve!: (v: MutationResult) => void; h.send.mockReturnValue(new Promise<MutationResult>(r => { resolve = r; })); const run = h.run(); expect(h.store.clearSettled(h.store.get()!)).toBe(false); await h.run(); expect(h.send).toHaveBeenCalledTimes(1); resolve(result); await run; expect(h.store.get()?.status).toBe('succeeded'); });
test.each([['FORBIDDEN', 403], ['REVISION_CONFLICT', 409], ['OPERATION_CONFLICT', 409], ['FOLDER_NOT_FOUND', 404], ['VALIDATION_FAILED', 422]])('初回%sは拒否、UNKNOWN後同応答は未確定を保持', async (code, status) => { const h = harness(); h.send.mockRejectedValueOnce(problem(code as string, status as number)); await h.run(); expect(h.store.get()?.status).toBe('rejected'); h.store.clearSettled(h.store.get()!); h.send.mockRejectedValueOnce(new Error('lost')); await h.run(); const body = h.store.get()!.request; h.send.mockRejectedValueOnce(problem(code as string, status as number)); await h.run(); expect(h.store.get()?.status).toBe('unknown'); expect(h.store.get()!.request).toBe(body); });
test.each([{ operationId: 'other' }, { resourceId: 'other' }, { changed: false }, { resultingRevision: 8 }, { resultingRevision: 9.5 }, { occurredAt: '2026-02-30T00:00:00Z' }, { occurredAt: '2026-10-07' }, null])('不正receipt %pはUNKNOWN', async patch => { const h = harness(); h.send.mockResolvedValue(patch === null ? null : { ...result, ...patch }); await h.run(); expect(h.store.get()?.status).toBe('unknown'); expect(h.invalidate).not.toHaveBeenCalled(); });
test('成功receipt後current read拒否をmutation失敗へ戻さない', async () => { const h = harness(); h.invalidate.mockRejectedValue(problem('FORBIDDEN', 403)); await h.run(); expect(h.store.get()).toMatchObject({ status: 'succeeded', result, refresh: 'failed' }); });
test('modeとgrant集合の同値を正規化しpresentationと行/action順をno-opに含めない', () => { const baseline = { ...policy, bindingMode: 'explicit' as const }; expect(policyChanged(baseline, { ...request, grants: [{ ...grant, actions: ['administer', 'read'] }] })).toBe(false); expect(policyChanged(policy, request)).toBe(true); expect(policyChanged(policy, { operationId: 'o', mode: 'inherit', expectedPolicyRevision: 8, reason: 'r' })).toBe(false); });
test.each([-1, 0.5, NaN, Infinity, Number.MAX_SAFE_INTEGER])('不正next policyRevision %pを送信しない', async revision => { const h = harness(); await expect(h.run({ ...request, expectedPolicyRevision: revision })).rejects.toThrow(/revision/); expect(h.send).not.toHaveBeenCalled(); });
test('no-opのMAX safe revisionはそのままreceipt照合できる', async () => { expect(policyRevisionError(Number.MAX_SAFE_INTEGER, false)).toBeNull(); const h = harness(); h.send.mockResolvedValue({ ...result, changed: false, resultingRevision: Number.MAX_SAFE_INTEGER }); await sendFolderAccessPolicyOperation({ store: h.store, context, targetFolderId: 'target', request: { ...request, expectedPolicyRevision: Number.MAX_SAFE_INTEGER }, baseline: { ...policy, bindingMode: 'explicit' }, send: h.send, invalidate: h.invalidate }); expect(h.store.get()?.status).toBe('succeeded'); });
test('Folder global resetでpolicy読取だけ消去しUNKNOWNをGCから独立して保持', async () => { const client = new QueryClient(); const store = folderAccessPolicyOperations(client); stores.push(store); const h = harness(); h.send.mockRejectedValue(new Error('lost')); await sendFolderAccessPolicyOperation({ store, context, targetFolderId: 'target', request, baseline: policy, send: h.send, invalidate: h.invalidate }); const saved = store.get(); client.setQueryData(['folder-access-policy', 'target'], policy); await refreshFolderMoveReads(client); expect(client.getQueryData(['folder-access-policy', 'target'])).toBeUndefined(); client.clear(); expect(folderAccessPolicyOperations(client).get()).toBe(saved); });
test('read検証は正確targetと5権限と三つ組を保持する', () => { expect(validateFolderPolicy(policy, 'target')).toBe(true); expect(validateFolderPolicy({ ...policy, target: { kind: 'document', id: 'target' } }, 'target')).toBe(false); expect(validateFolderPolicy({ ...policy, effectiveGrants: [{ ...policy.effectiveGrants[0]!, identityProvider: ' ' }] }, 'target')).toBe(false); });
test('fresh snapshotはlocal revisionが同じでもeffective source/grants/Folder移動を検知する', () => { const folder = { folderId: 'target', name: '資料', revision: 2, parentFolderId: 'parent', capabilities: { manageAccess: { status: 'available' } } } as FolderDetail; const baseline = { folder, policy }; expect(policySnapshotEqual(baseline, { folder, policy: { ...policy, effectiveSource: { kind: 'folder', id: 'other' } } })).toBe(false); expect(policySnapshotEqual(baseline, { folder: { ...folder, parentFolderId: 'other' }, policy })).toBe(false); });
test('Unicode照合で似た別subject IDもexact三つ組で集合比較し行順をno-opへ含めない', () => {
  const rows = ['é', 'e\u0301'].map(subjectId => ({ ...policy.effectiveGrants[0]!, subjectId }));
  expect(rows[0]!.subjectId).not.toBe(rows[1]!.subjectId);
  expect(policyChanged({ ...policy, bindingMode: 'explicit', effectiveGrants: rows }, { ...request, grants: [...rows].reverse() })).toBe(false);
});
