// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TextValue = {
    /**
     * 最大8192 UTF-8 bytes。サーバー側でbyte長も検証する。
     */
    text: string;
};

export type WorkSession = {
    principalId: string;
    displayName: string;
    actingAssignmentId: string;
    capabilities: {
        nativeWorkspace: boolean;
        agent: boolean;
        search: boolean;
        fileUpload: boolean;
        return: boolean;
    };
};

export type TaskSummary = {
    id: string;
    contextId: string;
    attemptId: string;
    revision: number;
    title: string;
    stepLabel: string;
    state: 'ready' | 'active' | 'held' | 'completed';
    canClaim: boolean;
    canEdit: boolean;
    canSubmit: boolean;
    handoffSnapshotId: string | null;
    attemptNumber: number;
    canReturn: boolean;
    returnInstructionId: string | null;
    returnTransition: ReturnTransition | null;
    canRegisterEvidence: boolean;
    canRegisterFinding: boolean;
    canRecordDecision: boolean;
};

export type WorkingArtifact = {
    id: string;
    taskId: string;
    attemptId: string;
    revision: number;
    schemaId: 'organization.text-draft.v1';
    value: TextValue;
    visibility: 'work_item_private';
};

export type InputResource = {
    kind: 'document';
    documentId: string;
    label: string;
};

export type HistoryEntry = {
    kind: string;
    occurredAt: string;
};

export type TaskDetail = {
    id: string;
    contextId: string;
    attemptId: string;
    revision: number;
    title: string;
    stepLabel: string;
    state: 'ready' | 'active' | 'held' | 'completed';
    canClaim: boolean;
    canEdit: boolean;
    canSubmit: boolean;
    handoffSnapshotId: string | null;
    inputResources: Array<InputResource>;
    history: Array<HistoryEntry>;
    workingArtifacts: Array<WorkingArtifact>;
    attemptNumber: number;
    canReturn: boolean;
    returnInstructionId: string | null;
    returnTransition: ReturnTransition | null;
    canRegisterEvidence: boolean;
    canRegisterFinding: boolean;
    canRecordDecision: boolean;
};

export type TaskPage = {
    items: Array<TaskSummary>;
    nextCursor: null;
};

export type PinnedArtifact = {
    artifactId: string;
    revision: number;
    schemaId: 'organization.text-draft.v1';
    value: TextValue;
};

export type HandoffSnapshot = {
    id: string;
    sourceTaskId: string;
    sourceAttemptId: string;
    targetTaskId: string;
    createdAt: string;
    artifacts: Array<PinnedArtifact>;
    workflowId: string;
    contextId: string;
    actingAssignmentId: string;
    submittedBy: 'sales-01' | 'office-01';
    submissionNumber: number;
    previousSubmissionId?: string;
    returnInstructionId?: string;
    evidenceRevisionRefs: Array<RevisionRef>;
    findingRevisionRefs: Array<RevisionRef>;
    decisionRevisionRefs: Array<RevisionRef>;
};

export type WorkCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
};

export type DraftCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    value: TextValue;
};

/**
 * Explicit immutable selection only. Missing added selection arrays mean empty for legacy commands. Combined record references <=100, without duplicates. Selected findings require all their evidence; selected decisions require their finding and all support. No records are automatically included.
 */
export type SubmitCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    artifacts: Array<{
        artifactId: string;
        revision: number;
    }>;
    evidenceRevisionRefs?: Array<RevisionRef>;
    findingRevisionRefs?: Array<RevisionRef>;
    decisionRevisionRefs?: Array<RevisionRef>;
    expectedAttemptId?: string;
};

export type DraftSaved = {
    kind: 'draft_saved';
    task: TaskSummary;
    artifact: WorkingArtifact;
};

export type Claimed = {
    kind: 'claimed';
    task: TaskSummary;
};

export type Submitted = {
    kind: 'submitted';
    task: TaskSummary;
    snapshot: HandoffSnapshot;
    nextTask: TaskSummary;
};

export type WorkResult = DraftSaved | Claimed | Submitted | Returned | EvidenceRegistered | FindingRegistered | DecisionRecorded;

export type Problem = {
    type: string;
    title: string;
    status: number;
    code: 'VALIDATION_FAILED' | 'FORBIDDEN' | 'WORK_ITEM_NOT_FOUND' | 'WORK_ARTIFACT_NOT_FOUND' | 'REVISION_CONFLICT' | 'OPERATION_CONFLICT' | 'WORK_ASSIGNMENT_CONFLICT' | 'HANDOFF_NOT_READY' | 'DEPENDENCY_UNAVAILABLE' | 'COMMIT_OUTCOME_UNKNOWN' | 'INTEGRITY_VIOLATION' | 'CURSOR_STALE' | 'EVIDENCE_NOT_FOUND' | 'FINDING_NOT_FOUND';
    traceId: string;
};

export type ArtifactPage = {
    items: Array<WorkingArtifact>;
    nextCursor: null;
};

export type ReturnTransition = {
    transitionId: string;
    targetTaskId: string;
    previousSubmissionId: string;
};

export type ReturnInstruction = {
    id: string;
    workflowId: string;
    contextId: string;
    sourceTaskId: string;
    sourceAttemptId: string;
    targetTaskId: string;
    targetAttemptId: string;
    previousSubmissionId: string;
    transitionId: string;
    actingAssignmentId: string;
    /**
     * 空白のみ不可、最大8192 UTF-8 bytes。
     */
    reason: string;
    returnedBy: 'office-01';
    createdAt: string;
};

export type ReturnCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    previousSubmissionId: string;
    targetTaskId: string;
    transitionId: string;
    /**
     * 空白のみ不可、最大8192 UTF-8 bytes。
     */
    reason: string;
};

export type Returned = {
    kind: 'returned';
    task: TaskSummary;
    returnInstruction: ReturnInstruction;
    nextTask: TaskSummary;
};

export type RevisionRef = {
    id: string;
    revision: 1;
};

export type SourceRef = {
    providerId: 'document';
    resourceId: string;
    revisionId: string;
    versionId: string;
};

export type AuthoritativeLocator = {
    kind: 'contentItem';
    contentItemId: string;
    representationId: string;
};

/**
 * Immutable reference-only source pointer. relevantLocation is human text and is not verified source content. Fragment is not retained; coverage is unknown. providerCheckedAt/retrievedAt describe completion of the server Document preflight, recordedAt is Work registration time. No cross-provider atomicity or retained source proof is asserted.
 */
export type EvidenceRecord = {
    id: string;
    revision: 1;
    contextId: string;
    taskId: string;
    attemptId: string;
    actingAssignmentId: string;
    visibility: 'work_item_private';
    createdBy: string;
    origin: 'human';
    sourceRef: SourceRef;
    authoritativeLocator: AuthoritativeLocator;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    relevantLocation: string;
    relevantLocationVerified: false;
    fragmentOmissionReason: 'not_retained';
    coverage: 'unknown';
    uncertainty: Array<string>;
    conflictReferences: Array<RevisionRef>;
    policyDisposition: 'reference_only';
    retrievedAt: string;
    recordedAt: string;
    providerCheckedAt: string;
};

export type Finding = {
    id: string;
    revision: 1;
    contextId: string;
    taskId: string;
    attemptId: string;
    actingAssignmentId: string;
    visibility: 'work_item_private';
    author: string;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    claim: string;
    evidenceRevisionRefs: Array<RevisionRef>;
    supersedesFindingId: string | null;
    uncertainty: Array<string>;
    conflicts: Array<RevisionRef>;
    createdAt: string;
};

export type HumanDecision = {
    id: string;
    revision: 1;
    contextId: string;
    taskId: string;
    attemptId: string;
    actingAssignmentId: string;
    visibility: 'work_item_private';
    findingId: string;
    findingRevision: 1;
    decision: 'accepted' | 'modified' | 'rejected';
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    adoptedClaim: string | null;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    reason: string | null;
    evidenceRevisionRefs: Array<RevisionRef>;
    humanPrincipal: string;
    createdAt: string;
    supersedesDecisionId: string | null;
};

export type EvidenceCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    sourceRef: SourceRef;
    authoritativeLocator: AuthoritativeLocator;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    relevantLocation: string;
};

export type FindingCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    claim: string;
    evidenceRevisionRefs: Array<RevisionRef>;
    supersedesFindingId?: string | null;
};

/**
 * HumanInteractive only. taskId and expectedAttemptId name the current judging task/attempt, including office judging a received sales Finding. modified requires a nonblank adoptedClaim; accepted/rejected omit it.
 */
export type DecisionCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    taskId: string;
    findingRevision: 1;
    decision: 'accepted' | 'modified' | 'rejected';
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    adoptedClaim?: string | null;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    reason?: string | null;
    evidenceRevisionRefs: Array<RevisionRef>;
    supersedesDecisionId?: string | null;
};

export type EvidenceRegistered = {
    kind: 'evidence_registered';
    task: TaskSummary;
    evidence: EvidenceRecord;
};

export type FindingRegistered = {
    kind: 'finding_registered';
    task: TaskSummary;
    finding: Finding;
};

export type DecisionRecorded = {
    kind: 'decision_recorded';
    task: TaskSummary;
    decision: HumanDecision;
};

export type EvidencePage = {
    items: Array<EvidenceRecord>;
    nextCursor: string | null;
};

export type FindingPage = {
    items: Array<Finding>;
    nextCursor: string | null;
};

export type DecisionPage = {
    items: Array<HumanDecision>;
    nextCursor: string | null;
};

export type GetOrganizationSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organization/session';
};

export type GetOrganizationSessionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetOrganizationSessionError = GetOrganizationSessionErrors[keyof GetOrganizationSessionErrors];

export type GetOrganizationSessionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkSession;
};

export type GetOrganizationSessionResponse = GetOrganizationSessionResponses[keyof GetOrganizationSessionResponses];

export type ListWorkItemsData = {
    body?: never;
    path?: never;
    query?: {
        view?: 'context' | 'queue';
        limit?: number;
        /**
         * この固定2step PoCはcursor非対応。指定するとCURSOR_STALE。
         */
        cursor?: string;
    };
    url: '/v1/organization/tasks';
};

export type ListWorkItemsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListWorkItemsError = ListWorkItemsErrors[keyof ListWorkItemsErrors];

export type ListWorkItemsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: TaskPage;
};

export type ListWorkItemsResponse = ListWorkItemsResponses[keyof ListWorkItemsResponses];

export type GetWorkItemData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}';
};

export type GetWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetWorkItemError = GetWorkItemErrors[keyof GetWorkItemErrors];

export type GetWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: TaskDetail;
};

export type GetWorkItemResponse = GetWorkItemResponses[keyof GetWorkItemResponses];

export type ListWorkingArtifactsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/working-artifacts';
};

export type ListWorkingArtifactsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListWorkingArtifactsError = ListWorkingArtifactsErrors[keyof ListWorkingArtifactsErrors];

export type ListWorkingArtifactsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: ArtifactPage;
};

export type ListWorkingArtifactsResponse = ListWorkingArtifactsResponses[keyof ListWorkingArtifactsResponses];

export type CreateWorkingArtifactData = {
    body: DraftCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/working-artifacts';
};

export type CreateWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type CreateWorkingArtifactError = CreateWorkingArtifactErrors[keyof CreateWorkingArtifactErrors];

export type CreateWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type CreateWorkingArtifactResponse = CreateWorkingArtifactResponses[keyof CreateWorkingArtifactResponses];

export type GetWorkingArtifactData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/working-artifacts/{id}';
};

export type GetWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetWorkingArtifactError = GetWorkingArtifactErrors[keyof GetWorkingArtifactErrors];

export type GetWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkingArtifact;
};

export type GetWorkingArtifactResponse = GetWorkingArtifactResponses[keyof GetWorkingArtifactResponses];

export type UpdateWorkingArtifactData = {
    body: DraftCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/working-artifacts/{id}';
};

export type UpdateWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type UpdateWorkingArtifactError = UpdateWorkingArtifactErrors[keyof UpdateWorkingArtifactErrors];

export type UpdateWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type UpdateWorkingArtifactResponse = UpdateWorkingArtifactResponses[keyof UpdateWorkingArtifactResponses];

export type ClaimWorkItemData = {
    body: WorkCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/claim';
};

export type ClaimWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ClaimWorkItemError = ClaimWorkItemErrors[keyof ClaimWorkItemErrors];

export type ClaimWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type ClaimWorkItemResponse = ClaimWorkItemResponses[keyof ClaimWorkItemResponses];

export type SubmitWorkItemData = {
    body: SubmitCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/submit';
};

export type SubmitWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type SubmitWorkItemError = SubmitWorkItemErrors[keyof SubmitWorkItemErrors];

export type SubmitWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type SubmitWorkItemResponse = SubmitWorkItemResponses[keyof SubmitWorkItemResponses];

export type GetHandoffSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/handoff-snapshots/{id}';
};

export type GetHandoffSnapshotErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetHandoffSnapshotError = GetHandoffSnapshotErrors[keyof GetHandoffSnapshotErrors];

export type GetHandoffSnapshotResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: HandoffSnapshot;
};

export type GetHandoffSnapshotResponse = GetHandoffSnapshotResponses[keyof GetHandoffSnapshotResponses];

export type RecoverOrganizationOperationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/operations/{id}';
};

export type RecoverOrganizationOperationErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RecoverOrganizationOperationError = RecoverOrganizationOperationErrors[keyof RecoverOrganizationOperationErrors];

export type RecoverOrganizationOperationResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RecoverOrganizationOperationResponse = RecoverOrganizationOperationResponses[keyof RecoverOrganizationOperationResponses];

export type ReturnOrganizationTaskData = {
    body: ReturnCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/return';
};

export type ReturnOrganizationTaskErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ReturnOrganizationTaskError = ReturnOrganizationTaskErrors[keyof ReturnOrganizationTaskErrors];

export type ReturnOrganizationTaskResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type ReturnOrganizationTaskResponse = ReturnOrganizationTaskResponses[keyof ReturnOrganizationTaskResponses];

export type GetOrganizationReturnInstructionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/return-instructions/{id}';
};

export type GetOrganizationReturnInstructionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetOrganizationReturnInstructionError = GetOrganizationReturnInstructionErrors[keyof GetOrganizationReturnInstructionErrors];

export type GetOrganizationReturnInstructionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: ReturnInstruction;
};

export type GetOrganizationReturnInstructionResponse = GetOrganizationReturnInstructionResponses[keyof GetOrganizationReturnInstructionResponses];

export type ListEvidenceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
        cursor?: string;
    };
    url: '/v1/organization/tasks/{id}/evidence';
};

export type ListEvidenceErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListEvidenceError = ListEvidenceErrors[keyof ListEvidenceErrors];

export type ListEvidenceResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: EvidencePage;
};

export type ListEvidenceResponse = ListEvidenceResponses[keyof ListEvidenceResponses];

export type RegisterEvidenceData = {
    body: EvidenceCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/evidence';
};

export type RegisterEvidenceErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RegisterEvidenceError = RegisterEvidenceErrors[keyof RegisterEvidenceErrors];

export type RegisterEvidenceResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RegisterEvidenceResponse = RegisterEvidenceResponses[keyof RegisterEvidenceResponses];

export type GetEvidenceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/evidence/{id}';
};

export type GetEvidenceErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetEvidenceError = GetEvidenceErrors[keyof GetEvidenceErrors];

export type GetEvidenceResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: EvidenceRecord;
};

export type GetEvidenceResponse = GetEvidenceResponses[keyof GetEvidenceResponses];

export type ListFindingsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
        cursor?: string;
    };
    url: '/v1/organization/tasks/{id}/findings';
};

export type ListFindingsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListFindingsError = ListFindingsErrors[keyof ListFindingsErrors];

export type ListFindingsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: FindingPage;
};

export type ListFindingsResponse = ListFindingsResponses[keyof ListFindingsResponses];

export type RegisterFindingData = {
    body: FindingCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/findings';
};

export type RegisterFindingErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RegisterFindingError = RegisterFindingErrors[keyof RegisterFindingErrors];

export type RegisterFindingResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RegisterFindingResponse = RegisterFindingResponses[keyof RegisterFindingResponses];

export type GetFindingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/findings/{id}';
};

export type GetFindingErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetFindingError = GetFindingErrors[keyof GetFindingErrors];

export type GetFindingResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: Finding;
};

export type GetFindingResponse = GetFindingResponses[keyof GetFindingResponses];

export type ListHumanDecisionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
        cursor?: string;
    };
    url: '/v1/organization/findings/{id}/decisions';
};

export type ListHumanDecisionsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListHumanDecisionsError = ListHumanDecisionsErrors[keyof ListHumanDecisionsErrors];

export type ListHumanDecisionsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: DecisionPage;
};

export type ListHumanDecisionsResponse = ListHumanDecisionsResponses[keyof ListHumanDecisionsResponses];

export type RecordHumanDecisionData = {
    body: DecisionCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/findings/{id}/decisions';
};

export type RecordHumanDecisionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RecordHumanDecisionError = RecordHumanDecisionErrors[keyof RecordHumanDecisionErrors];

export type RecordHumanDecisionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RecordHumanDecisionResponse = RecordHumanDecisionResponses[keyof RecordHumanDecisionResponses];
