// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TextValue = {
    /**
     * 最大8192 UTF-8 bytes。サーバー側でbyte長も検証する。
     */
    text: string;
};

export type WorkSession = {
    principalId: string;
    displayName: string;
    actingAssignmentId: string;
    capabilities: {
        nativeWorkspace: boolean;
        agent: boolean;
        search: boolean;
        fileUpload: boolean;
        return: boolean;
    };
};

export type TaskSummary = {
    id: string;
    contextId: string;
    attemptId: string;
    revision: number;
    title: string;
    stepLabel: string;
    state: 'ready' | 'active' | 'held' | 'completed';
    canClaim: boolean;
    canEdit: boolean;
    canSubmit: boolean;
    handoffSnapshotId: string | null;
};

export type WorkingArtifact = {
    id: string;
    taskId: string;
    attemptId: string;
    revision: number;
    schemaId: 'organization.text-draft.v1';
    value: TextValue;
    visibility: 'work_item_private';
};

export type InputResource = {
    kind: 'document';
    documentId: string;
    label: string;
};

export type HistoryEntry = {
    kind: string;
    occurredAt: string;
};

export type TaskDetail = {
    id: string;
    contextId: string;
    attemptId: string;
    revision: number;
    title: string;
    stepLabel: string;
    state: 'ready' | 'active' | 'held' | 'completed';
    canClaim: boolean;
    canEdit: boolean;
    canSubmit: boolean;
    handoffSnapshotId: string | null;
    inputResources: Array<InputResource>;
    history: Array<HistoryEntry>;
    workingArtifacts: Array<WorkingArtifact>;
};

export type TaskPage = {
    items: Array<TaskSummary>;
    nextCursor: null;
};

export type PinnedArtifact = {
    artifactId: string;
    revision: number;
    schemaId: 'organization.text-draft.v1';
    value: TextValue;
};

export type HandoffSnapshot = {
    id: string;
    sourceTaskId: string;
    sourceAttemptId: string;
    targetTaskId: string;
    createdAt: string;
    artifacts: Array<PinnedArtifact>;
    workflowId: string;
    contextId: string;
    actingAssignmentId: string;
    submittedBy: 'sales-01' | 'office-01';
    submissionNumber: number;
};

export type WorkCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
};

export type DraftCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    value: TextValue;
};

export type SubmitCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    artifacts: Array<{
        artifactId: string;
        revision: number;
    }>;
};

export type DraftSaved = {
    kind: 'draft_saved';
    task: TaskSummary;
    artifact: WorkingArtifact;
};

export type Claimed = {
    kind: 'claimed';
    task: TaskSummary;
};

export type Submitted = {
    kind: 'submitted';
    task: TaskSummary;
    snapshot: HandoffSnapshot;
    nextTask: TaskSummary;
};

export type WorkResult = DraftSaved | Claimed | Submitted;

export type Problem = {
    type: string;
    title: string;
    status: number;
    code: 'VALIDATION_FAILED' | 'FORBIDDEN' | 'WORK_ITEM_NOT_FOUND' | 'WORK_ARTIFACT_NOT_FOUND' | 'REVISION_CONFLICT' | 'OPERATION_CONFLICT' | 'WORK_ASSIGNMENT_CONFLICT' | 'HANDOFF_NOT_READY' | 'DEPENDENCY_UNAVAILABLE' | 'COMMIT_OUTCOME_UNKNOWN' | 'INTEGRITY_VIOLATION' | 'CURSOR_STALE';
    traceId: string;
};

export type ArtifactPage = {
    items: Array<WorkingArtifact>;
    nextCursor: null;
};

export type GetOrganizationSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organization/session';
};

export type GetOrganizationSessionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetOrganizationSessionError = GetOrganizationSessionErrors[keyof GetOrganizationSessionErrors];

export type GetOrganizationSessionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkSession;
};

export type GetOrganizationSessionResponse = GetOrganizationSessionResponses[keyof GetOrganizationSessionResponses];

export type ListWorkItemsData = {
    body?: never;
    path?: never;
    query?: {
        view?: 'context' | 'queue';
        limit?: number;
        /**
         * この固定2step PoCはcursor非対応。指定するとCURSOR_STALE。
         */
        cursor?: string;
    };
    url: '/v1/organization/tasks';
};

export type ListWorkItemsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListWorkItemsError = ListWorkItemsErrors[keyof ListWorkItemsErrors];

export type ListWorkItemsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: TaskPage;
};

export type ListWorkItemsResponse = ListWorkItemsResponses[keyof ListWorkItemsResponses];

export type GetWorkItemData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}';
};

export type GetWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetWorkItemError = GetWorkItemErrors[keyof GetWorkItemErrors];

export type GetWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: TaskDetail;
};

export type GetWorkItemResponse = GetWorkItemResponses[keyof GetWorkItemResponses];

export type ListWorkingArtifactsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/working-artifacts';
};

export type ListWorkingArtifactsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListWorkingArtifactsError = ListWorkingArtifactsErrors[keyof ListWorkingArtifactsErrors];

export type ListWorkingArtifactsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: ArtifactPage;
};

export type ListWorkingArtifactsResponse = ListWorkingArtifactsResponses[keyof ListWorkingArtifactsResponses];

export type CreateWorkingArtifactData = {
    body: DraftCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/working-artifacts';
};

export type CreateWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type CreateWorkingArtifactError = CreateWorkingArtifactErrors[keyof CreateWorkingArtifactErrors];

export type CreateWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type CreateWorkingArtifactResponse = CreateWorkingArtifactResponses[keyof CreateWorkingArtifactResponses];

export type GetWorkingArtifactData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/working-artifacts/{id}';
};

export type GetWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetWorkingArtifactError = GetWorkingArtifactErrors[keyof GetWorkingArtifactErrors];

export type GetWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkingArtifact;
};

export type GetWorkingArtifactResponse = GetWorkingArtifactResponses[keyof GetWorkingArtifactResponses];

export type UpdateWorkingArtifactData = {
    body: DraftCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/working-artifacts/{id}';
};

export type UpdateWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type UpdateWorkingArtifactError = UpdateWorkingArtifactErrors[keyof UpdateWorkingArtifactErrors];

export type UpdateWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type UpdateWorkingArtifactResponse = UpdateWorkingArtifactResponses[keyof UpdateWorkingArtifactResponses];

export type ClaimWorkItemData = {
    body: WorkCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/claim';
};

export type ClaimWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ClaimWorkItemError = ClaimWorkItemErrors[keyof ClaimWorkItemErrors];

export type ClaimWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type ClaimWorkItemResponse = ClaimWorkItemResponses[keyof ClaimWorkItemResponses];

export type SubmitWorkItemData = {
    body: SubmitCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/submit';
};

export type SubmitWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type SubmitWorkItemError = SubmitWorkItemErrors[keyof SubmitWorkItemErrors];

export type SubmitWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type SubmitWorkItemResponse = SubmitWorkItemResponses[keyof SubmitWorkItemResponses];

export type GetHandoffSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/handoff-snapshots/{id}';
};

export type GetHandoffSnapshotErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetHandoffSnapshotError = GetHandoffSnapshotErrors[keyof GetHandoffSnapshotErrors];

export type GetHandoffSnapshotResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: HandoffSnapshot;
};

export type GetHandoffSnapshotResponse = GetHandoffSnapshotResponses[keyof GetHandoffSnapshotResponses];

export type RecoverOrganizationOperationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/operations/{id}';
};

export type RecoverOrganizationOperationErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RecoverOrganizationOperationError = RecoverOrganizationOperationErrors[keyof RecoverOrganizationOperationErrors];

export type RecoverOrganizationOperationResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RecoverOrganizationOperationResponse = RecoverOrganizationOperationResponses[keyof RecoverOrganizationOperationResponses];
