// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type TextValue = {
    /**
     * 最大8192 UTF-8 bytes。サーバー側でbyte長も検証する。
     */
    text: string;
};

export type WorkSession = {
    principalId: string;
    displayName: string;
    /**
     * 既定の実行担当。現在有効な責任がなければnull。
     */
    actingAssignmentId: string | null;
    capabilities: {
        nativeWorkspace: boolean;
        agent: boolean;
        search: boolean;
        fileUpload: boolean;
        return: boolean;
    };
    /**
     * nullはpolicyを現在評価できないことを示す（空の許可ではない）。
     */
    responsibilities: Array<Responsibility> | null;
    canManageOrganization: boolean;
    /**
     * 担当・委任操作のexpectedRevision。policyを評価できない場合null。
     */
    policyRevision: number | null;
};

export type TaskSummary = {
    id: string;
    contextId: string;
    attemptId: string;
    revision: number;
    title: string;
    stepLabel: string;
    state: 'ready' | 'active' | 'held' | 'completed';
    canClaim: boolean;
    canEdit: boolean;
    canSubmit: boolean;
    handoffSnapshotId: string | null;
    attemptNumber: number;
    canReturn: boolean;
    returnInstructionId: string | null;
    returnTransition: ReturnTransition | null;
    canRegisterEvidence: boolean;
    canRegisterFinding: boolean;
    canRecordDecision: boolean;
    canRequestAgent: boolean;
    canComplete: boolean;
    completionActionId: string | null;
    canHold: boolean;
    holdActionId: string | null;
    canResume: boolean;
    resumeActionId: string | null;
    requiredRoleId: string | null;
    claimAssignmentId: string | null;
    canAssign: boolean;
    assignment: TaskAssignmentView | null;
};

export type WorkingArtifact = {
    id: string;
    taskId: string;
    attemptId: string;
    revision: number;
    schemaId: 'organization.text-draft.v1';
    value: TextValue;
    visibility: 'work_item_private';
};

export type InputResource = {
    kind: 'document';
    documentId: string;
    label: string;
};

export type HistoryEntry = {
    kind: string;
    occurredAt: string;
};

export type TaskDetail = {
    id: string;
    contextId: string;
    attemptId: string;
    revision: number;
    title: string;
    stepLabel: string;
    state: 'ready' | 'active' | 'held' | 'completed';
    canClaim: boolean;
    canEdit: boolean;
    canSubmit: boolean;
    handoffSnapshotId: string | null;
    inputResources: Array<InputResource>;
    history: Array<HistoryEntry>;
    workingArtifacts: Array<WorkingArtifact>;
    attemptNumber: number;
    canReturn: boolean;
    returnInstructionId: string | null;
    returnTransition: ReturnTransition | null;
    canRegisterEvidence: boolean;
    canRegisterFinding: boolean;
    canRecordDecision: boolean;
    canRequestAgent: boolean;
    agentExecutionIds: Array<string>;
    canComplete: boolean;
    completionActionId: string | null;
    canHold: boolean;
    holdActionId: string | null;
    canResume: boolean;
    resumeActionId: string | null;
    requiredRoleId: string | null;
    claimAssignmentId: string | null;
    canAssign: boolean;
    assignment: TaskAssignmentView | null;
};

export type TaskPage = {
    items: Array<TaskSummary>;
    nextCursor: null;
};

export type PinnedArtifact = {
    artifactId: string;
    revision: number;
    schemaId: 'organization.text-draft.v1';
    value: TextValue;
};

export type HandoffSnapshot = {
    id: string;
    sourceTaskId: string;
    sourceAttemptId: string;
    targetTaskId: string;
    createdAt: string;
    artifacts: Array<PinnedArtifact>;
    workflowId: string;
    contextId: string;
    actingAssignmentId: string;
    submittedBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    submissionNumber: number;
    previousSubmissionId?: string;
    returnInstructionId?: string;
    evidenceRevisionRefs: Array<RevisionRef>;
    findingRevisionRefs: Array<RevisionRef>;
    decisionRevisionRefs: Array<RevisionRef>;
};

export type WorkCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
};

export type DraftCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    value: TextValue;
};

/**
 * Explicit immutable selection only. Missing added selection arrays mean empty for legacy commands. Combined record references <=100, without duplicates. Selected findings require all their evidence; selected decisions require their finding and all support. No records are automatically included.
 */
export type SubmitCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    artifacts: Array<{
        artifactId: string;
        revision: number;
    }>;
    evidenceRevisionRefs?: Array<RevisionRef>;
    findingRevisionRefs?: Array<RevisionRef>;
    decisionRevisionRefs?: Array<RevisionRef>;
    expectedAttemptId?: string;
};

export type DraftSaved = {
    kind: 'draft_saved';
    task: TaskSummary;
    artifact: WorkingArtifact;
};

export type Claimed = {
    kind: 'claimed';
    task: TaskSummary;
};

export type Submitted = {
    kind: 'submitted';
    task: TaskSummary;
    snapshot: HandoffSnapshot;
    nextTask: TaskSummary;
};

export type WorkResult = DraftSaved | Claimed | Submitted | Returned | EvidenceRegistered | FindingRegistered | DecisionRecorded | AgentExecutionRequested | AgentExecutionCancelled | Completed | Held | Resumed | Assigned | RoleAssignmentCreated | RoleAssignmentRevoked | DelegationCreated | DelegationRevoked;

export type Problem = {
    type: string;
    title: string;
    status: number;
    code: 'VALIDATION_FAILED' | 'FORBIDDEN' | 'WORK_ITEM_NOT_FOUND' | 'WORK_ARTIFACT_NOT_FOUND' | 'REVISION_CONFLICT' | 'OPERATION_CONFLICT' | 'WORK_ASSIGNMENT_CONFLICT' | 'HANDOFF_NOT_READY' | 'DEPENDENCY_UNAVAILABLE' | 'COMMIT_OUTCOME_UNKNOWN' | 'INTEGRITY_VIOLATION' | 'CURSOR_STALE' | 'EVIDENCE_NOT_FOUND' | 'FINDING_NOT_FOUND' | 'AGENT_RESULT_NOT_READY' | 'WORK_CONTEXT_STALE' | 'ORGANIZATION_RECORD_NOT_FOUND';
    traceId: string;
};

export type ArtifactPage = {
    items: Array<WorkingArtifact>;
    nextCursor: null;
};

export type ReturnTransition = {
    transitionId: string;
    targetTaskId: string;
    previousSubmissionId: string;
};

export type ReturnInstruction = {
    id: string;
    workflowId: string;
    contextId: string;
    sourceTaskId: string;
    sourceAttemptId: string;
    targetTaskId: string;
    targetAttemptId: string;
    previousSubmissionId: string;
    transitionId: string;
    actingAssignmentId: string;
    /**
     * 空白のみ不可、最大8192 UTF-8 bytes。
     */
    reason: string;
    returnedBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    createdAt: string;
};

export type ReturnCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    previousSubmissionId: string;
    targetTaskId: string;
    transitionId: string;
    /**
     * 空白のみ不可、最大8192 UTF-8 bytes。
     */
    reason: string;
};

export type Returned = {
    kind: 'returned';
    task: TaskSummary;
    returnInstruction: ReturnInstruction;
    nextTask: TaskSummary;
};

export type RevisionRef = {
    id: string;
    revision: 1;
};

export type SourceRef = {
    providerId: 'document';
    resourceId: string;
    revisionId: string;
    versionId: string;
};

export type AuthoritativeLocator = {
    kind: 'contentItem';
    contentItemId: string;
    representationId: string;
};

/**
 * Immutable reference-only source pointer. relevantLocation is human text and is not verified source content. Fragment is not retained; coverage is unknown. providerCheckedAt/retrievedAt describe completion of the server Document preflight, recordedAt is Work registration time. No cross-provider atomicity or retained source proof is asserted.
 */
export type EvidenceRecord = {
    id: string;
    revision: 1;
    contextId: string;
    taskId: string;
    attemptId: string;
    actingAssignmentId: string;
    visibility: 'work_item_private';
    createdBy: string;
    origin: 'human';
    sourceRef: SourceRef;
    authoritativeLocator: AuthoritativeLocator;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    relevantLocation: string;
    relevantLocationVerified: false;
    fragmentOmissionReason: 'not_retained';
    coverage: 'unknown';
    uncertainty: Array<string>;
    conflictReferences: Array<RevisionRef>;
    policyDisposition: 'reference_only';
    retrievedAt: string;
    recordedAt: string;
    providerCheckedAt: string;
};

export type Finding = {
    id: string;
    revision: 1;
    contextId: string;
    taskId: string;
    attemptId: string;
    actingAssignmentId: string;
    visibility: 'work_item_private';
    author: string;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    claim: string;
    evidenceRevisionRefs: Array<RevisionRef>;
    supersedesFindingId: string | null;
    uncertainty: Array<string>;
    conflicts: Array<RevisionRef>;
    createdAt: string;
    originExecutionId?: string;
};

export type HumanDecision = {
    id: string;
    revision: 1;
    contextId: string;
    taskId: string;
    attemptId: string;
    actingAssignmentId: string;
    visibility: 'work_item_private';
    findingId: string;
    findingRevision: 1;
    decision: 'accepted' | 'modified' | 'rejected';
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    adoptedClaim: string | null;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    reason: string | null;
    evidenceRevisionRefs: Array<RevisionRef>;
    humanPrincipal: string;
    createdAt: string;
    supersedesDecisionId: string | null;
};

export type EvidenceCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    sourceRef: SourceRef;
    authoritativeLocator: AuthoritativeLocator;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    relevantLocation: string;
};

export type FindingCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    claim: string;
    evidenceRevisionRefs: Array<RevisionRef>;
    supersedesFindingId?: string | null;
};

/**
 * HumanInteractive only. taskId and expectedAttemptId name the current judging task/attempt, including office judging a received sales Finding. modified requires a nonblank adoptedClaim; accepted/rejected omit it.
 */
export type DecisionCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    taskId: string;
    findingRevision: 1;
    decision: 'accepted' | 'modified' | 'rejected';
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    adoptedClaim?: string | null;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    reason?: string | null;
    evidenceRevisionRefs: Array<RevisionRef>;
    supersedesDecisionId?: string | null;
};

export type EvidenceRegistered = {
    kind: 'evidence_registered';
    task: TaskSummary;
    evidence: EvidenceRecord;
};

export type FindingRegistered = {
    kind: 'finding_registered';
    task: TaskSummary;
    finding: Finding;
};

export type DecisionRecorded = {
    kind: 'decision_recorded';
    task: TaskSummary;
    decision: HumanDecision;
};

export type EvidencePage = {
    items: Array<EvidenceRecord>;
    nextCursor: string | null;
};

export type FindingPage = {
    items: Array<Finding>;
    nextCursor: string | null;
};

export type DecisionPage = {
    items: Array<HumanDecision>;
    nextCursor: string | null;
};

export type ProviderPrincipalBinding = {
    providerId: 'document';
    principalId: 'poc/poc-agent';
    invocationKind: 'agent';
};

export type AgentResult = {
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    summary: string;
    findingRevisionRefs: [
        RevisionRef
    ];
    evidenceRevisionRefs: Array<RevisionRef>;
    uncertainty: Array<string>;
    simulated: true;
    bodyAnalyzed: false;
    liveLlm: false;
    mcpWireExecuted: false;
};

export type AgentExecution = {
    id: string;
    contextId: string;
    workItemId: string;
    attemptId: string;
    requestedBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    requesterResponsibility: string;
    executedBy: 'organization-synthetic/agent-01';
    executorInvocationKind: 'agent';
    providerPrincipalBindings: [
        ProviderPrincipalBinding
    ];
    effectiveContextRevision: number;
    taskRevision: number;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    purpose: string;
    evidenceRevisionRefs: Array<RevisionRef>;
    status: 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled' | 'outcome_unknown';
    startedAt: string;
    endedAt: string | null;
    result: AgentResult | null;
    failureCode: 'provider_denied' | 'context_stale' | 'invalid_output' | 'dependency_unavailable' | 'interrupted' | 'commit_outcome_unknown' | null;
};

export type AgentExecutionRequest = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    /**
     * UTF-8 encoded length is limited to 8192 bytes by the server.
     */
    purpose: string;
    evidenceRevisionRefs: Array<RevisionRef>;
};

export type CancelAgentExecution = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    taskId: string;
};

export type AgentExecutionRequested = {
    kind: 'agent_execution_requested';
    task: TaskSummary;
    execution: AgentExecution;
};

export type AgentExecutionCancelled = {
    kind: 'agent_execution_cancelled';
    task: TaskSummary;
    execution: AgentExecution;
};

/**
 * 定義済みの完了・保留・再開だけを受け付ける。現在担当・試行・revision・定義actionを再確認し、保留と再開では同じ試行・担当・保存内容を保持する。
 */
export type WorkflowActionCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    action: 'complete' | 'hold' | 'resume';
    definitionActionId: string;
};

export type Completed = {
    kind: 'completed';
    task: TaskSummary;
};

export type Held = {
    kind: 'held';
    task: TaskSummary;
};

export type Resumed = {
    kind: 'resumed';
    task: TaskSummary;
};

export type PolicyAction = 'context.read' | 'context.progress.read' | 'context.history.read' | 'queue.read' | 'work.read' | 'work.claim' | 'work.assign' | 'work.edit' | 'work.submit' | 'work.return' | 'work.complete' | 'work.hold' | 'work.resume' | 'evidence.register' | 'finding.register' | 'decision.record' | 'agent.request' | 'organization.manage';

/**
 * 評価時点で有効な責任の説明。再利用できる許可ではない。
 */
export type Responsibility = {
    id: string;
    kind: 'role_assignment' | 'delegation';
    principal: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    roleId: string;
    roleLabel: string;
    unitId: string;
    unitLabel: string;
    actions: Array<PolicyAction>;
    validFrom: string;
    validUntil: string | null;
    sourceAssignmentId: string | null;
    delegator: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01' | null;
};

export type OrganizationalUnit = {
    id: string;
    label: string;
    defaultArchetype: 'context' | 'queue';
    roleIds: Array<string>;
};

export type BusinessRole = {
    id: string;
    key: string;
    label: string;
    actions: Array<PolicyAction>;
};

export type RoleAssignment = {
    id: string;
    principal: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    roleId: string;
    unitId: string;
    validFrom: string;
    validUntil: string | null;
    reason: string;
    createdBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01' | null;
    createdAt: string;
    revokedAt: string | null;
    revokedBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01' | null;
    revokeReason: string | null;
};

export type Delegation = {
    id: string;
    sourceAssignmentId: string;
    delegator: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    recipient: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    actions: Array<PolicyAction>;
    validFrom: string;
    validUntil: string;
    reason: string;
    createdBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    createdAt: string;
    revokedAt: string | null;
    revokedBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01' | null;
    revokeReason: string | null;
};

/**
 * 現在の担当者本人と現在のwork.assign保有者にだけ返す。
 */
export type TaskAssignmentView = {
    principalId: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    displayName: string;
    actingAssignmentId: string;
    actingKind: 'role_assignment' | 'delegation' | null;
    roleLabel: string | null;
    delegatorPrincipalId: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01' | null;
    responsibilityEffective: boolean;
};

export type WorkAssignmentRecord = {
    id: string;
    taskId: string;
    attemptId: string;
    principal: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    actingAssignmentId: string;
    assignedBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01' | null;
    managerAssignmentId: string | null;
    reason: string | null;
    startedAt: string;
    endedAt: string | null;
    endedBy: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01' | null;
};

export type UnitPage = {
    items: Array<OrganizationalUnit>;
    nextCursor: null;
};

export type RolePage = {
    items: Array<BusinessRole>;
    nextCursor: null;
};

export type RoleAssignmentPage = {
    items: Array<RoleAssignment>;
    nextCursor: null;
};

export type DelegationPage = {
    items: Array<Delegation>;
    nextCursor: null;
};

/**
 * expectedRevisionはOrganization policyのrevision。actingAssignmentIdは現在有効な業務管理の正式割当。
 */
export type RoleAssignmentCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    principalId: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    roleId: string;
    unitId: string;
    validFrom?: string;
    validUntil?: string;
    /**
     * 空白のみ不可、最大1024 UTF-8 bytes。
     */
    reason: string;
};

export type RevokePolicyRecordCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    /**
     * 空白のみ不可、最大1024 UTF-8 bytes。
     */
    reason: string;
};

/**
 * 委任元の正式割当より広い操作・長い期限・再委任は拒否。organization.manageとwork.assignは委任不可。
 */
export type DelegationCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    sourceAssignmentId: string;
    recipientPrincipalId: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    actions: Array<PolicyAction>;
    validFrom?: string;
    validUntil: string;
    /**
     * 空白のみ不可、最大1024 UTF-8 bytes。
     */
    reason: string;
};

/**
 * expectedRevisionはタスクのrevision。新担当者の責任は工程の役割とwork.claimを含み現在有効であること。
 */
export type AssignmentCommand = {
    operationId: string;
    expectedRevision: number;
    actingAssignmentId: string;
    expectedAttemptId: string;
    assigneePrincipalId: 'sales-01' | 'office-01' | 'review-01' | 'approver-01' | 'multi-role-01' | 'delegate-01';
    assigneeResponsibilityId: string;
    reason: string;
};

export type Assigned = {
    kind: 'assigned';
    task: TaskSummary;
    assignment: WorkAssignmentRecord;
};

export type RoleAssignmentCreated = {
    kind: 'role_assignment_created';
    assignment: RoleAssignment;
    policyRevision: number;
};

export type RoleAssignmentRevoked = {
    kind: 'role_assignment_revoked';
    assignment: RoleAssignment;
    policyRevision: number;
};

export type DelegationCreated = {
    kind: 'delegation_created';
    delegation: Delegation;
    policyRevision: number;
};

export type DelegationRevoked = {
    kind: 'delegation_revoked';
    delegation: Delegation;
    policyRevision: number;
};

export type GetOrganizationSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organization/session';
};

export type GetOrganizationSessionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetOrganizationSessionError = GetOrganizationSessionErrors[keyof GetOrganizationSessionErrors];

export type GetOrganizationSessionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkSession;
};

export type GetOrganizationSessionResponse = GetOrganizationSessionResponses[keyof GetOrganizationSessionResponses];

export type ListWorkItemsData = {
    body?: never;
    path?: never;
    query?: {
        view?: 'context' | 'queue';
        limit?: number;
        /**
         * この固定2step PoCはcursor非対応。指定するとCURSOR_STALE。
         */
        cursor?: string;
        /**
         * 表示範囲とする本人の現在有効な責任。省略時は全有効責任の和。本人のものでなければFORBIDDEN。
         */
        actingAssignmentId?: string;
    };
    url: '/v1/organization/tasks';
};

export type ListWorkItemsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListWorkItemsError = ListWorkItemsErrors[keyof ListWorkItemsErrors];

export type ListWorkItemsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: TaskPage;
};

export type ListWorkItemsResponse = ListWorkItemsResponses[keyof ListWorkItemsResponses];

export type GetWorkItemData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}';
};

export type GetWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetWorkItemError = GetWorkItemErrors[keyof GetWorkItemErrors];

export type GetWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: TaskDetail;
};

export type GetWorkItemResponse = GetWorkItemResponses[keyof GetWorkItemResponses];

export type ListWorkingArtifactsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/working-artifacts';
};

export type ListWorkingArtifactsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListWorkingArtifactsError = ListWorkingArtifactsErrors[keyof ListWorkingArtifactsErrors];

export type ListWorkingArtifactsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: ArtifactPage;
};

export type ListWorkingArtifactsResponse = ListWorkingArtifactsResponses[keyof ListWorkingArtifactsResponses];

export type CreateWorkingArtifactData = {
    body: DraftCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/working-artifacts';
};

export type CreateWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type CreateWorkingArtifactError = CreateWorkingArtifactErrors[keyof CreateWorkingArtifactErrors];

export type CreateWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type CreateWorkingArtifactResponse = CreateWorkingArtifactResponses[keyof CreateWorkingArtifactResponses];

export type GetWorkingArtifactData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/working-artifacts/{id}';
};

export type GetWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetWorkingArtifactError = GetWorkingArtifactErrors[keyof GetWorkingArtifactErrors];

export type GetWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkingArtifact;
};

export type GetWorkingArtifactResponse = GetWorkingArtifactResponses[keyof GetWorkingArtifactResponses];

export type UpdateWorkingArtifactData = {
    body: DraftCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/working-artifacts/{id}';
};

export type UpdateWorkingArtifactErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type UpdateWorkingArtifactError = UpdateWorkingArtifactErrors[keyof UpdateWorkingArtifactErrors];

export type UpdateWorkingArtifactResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type UpdateWorkingArtifactResponse = UpdateWorkingArtifactResponses[keyof UpdateWorkingArtifactResponses];

export type ClaimWorkItemData = {
    body: WorkCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/claim';
};

export type ClaimWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ClaimWorkItemError = ClaimWorkItemErrors[keyof ClaimWorkItemErrors];

export type ClaimWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type ClaimWorkItemResponse = ClaimWorkItemResponses[keyof ClaimWorkItemResponses];

export type SubmitWorkItemData = {
    body: SubmitCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/submit';
};

export type SubmitWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type SubmitWorkItemError = SubmitWorkItemErrors[keyof SubmitWorkItemErrors];

export type SubmitWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type SubmitWorkItemResponse = SubmitWorkItemResponses[keyof SubmitWorkItemResponses];

export type GetHandoffSnapshotData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/handoff-snapshots/{id}';
};

export type GetHandoffSnapshotErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetHandoffSnapshotError = GetHandoffSnapshotErrors[keyof GetHandoffSnapshotErrors];

export type GetHandoffSnapshotResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: HandoffSnapshot;
};

export type GetHandoffSnapshotResponse = GetHandoffSnapshotResponses[keyof GetHandoffSnapshotResponses];

export type RecoverOrganizationOperationData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/operations/{id}';
};

export type RecoverOrganizationOperationErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RecoverOrganizationOperationError = RecoverOrganizationOperationErrors[keyof RecoverOrganizationOperationErrors];

export type RecoverOrganizationOperationResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RecoverOrganizationOperationResponse = RecoverOrganizationOperationResponses[keyof RecoverOrganizationOperationResponses];

export type ReturnOrganizationTaskData = {
    body: ReturnCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/return';
};

export type ReturnOrganizationTaskErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ReturnOrganizationTaskError = ReturnOrganizationTaskErrors[keyof ReturnOrganizationTaskErrors];

export type ReturnOrganizationTaskResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type ReturnOrganizationTaskResponse = ReturnOrganizationTaskResponses[keyof ReturnOrganizationTaskResponses];

export type GetOrganizationReturnInstructionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/return-instructions/{id}';
};

export type GetOrganizationReturnInstructionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetOrganizationReturnInstructionError = GetOrganizationReturnInstructionErrors[keyof GetOrganizationReturnInstructionErrors];

export type GetOrganizationReturnInstructionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: ReturnInstruction;
};

export type GetOrganizationReturnInstructionResponse = GetOrganizationReturnInstructionResponses[keyof GetOrganizationReturnInstructionResponses];

export type ListEvidenceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
        cursor?: string;
    };
    url: '/v1/organization/tasks/{id}/evidence';
};

export type ListEvidenceErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListEvidenceError = ListEvidenceErrors[keyof ListEvidenceErrors];

export type ListEvidenceResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: EvidencePage;
};

export type ListEvidenceResponse = ListEvidenceResponses[keyof ListEvidenceResponses];

export type RegisterEvidenceData = {
    body: EvidenceCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/evidence';
};

export type RegisterEvidenceErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RegisterEvidenceError = RegisterEvidenceErrors[keyof RegisterEvidenceErrors];

export type RegisterEvidenceResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RegisterEvidenceResponse = RegisterEvidenceResponses[keyof RegisterEvidenceResponses];

export type GetEvidenceData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/evidence/{id}';
};

export type GetEvidenceErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetEvidenceError = GetEvidenceErrors[keyof GetEvidenceErrors];

export type GetEvidenceResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: EvidenceRecord;
};

export type GetEvidenceResponse = GetEvidenceResponses[keyof GetEvidenceResponses];

export type ListFindingsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
        cursor?: string;
    };
    url: '/v1/organization/tasks/{id}/findings';
};

export type ListFindingsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListFindingsError = ListFindingsErrors[keyof ListFindingsErrors];

export type ListFindingsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: FindingPage;
};

export type ListFindingsResponse = ListFindingsResponses[keyof ListFindingsResponses];

export type RegisterFindingData = {
    body: FindingCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/findings';
};

export type RegisterFindingErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RegisterFindingError = RegisterFindingErrors[keyof RegisterFindingErrors];

export type RegisterFindingResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RegisterFindingResponse = RegisterFindingResponses[keyof RegisterFindingResponses];

export type GetFindingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/findings/{id}';
};

export type GetFindingErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetFindingError = GetFindingErrors[keyof GetFindingErrors];

export type GetFindingResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: Finding;
};

export type GetFindingResponse = GetFindingResponses[keyof GetFindingResponses];

export type ListHumanDecisionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        limit?: number;
        cursor?: string;
    };
    url: '/v1/organization/findings/{id}/decisions';
};

export type ListHumanDecisionsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListHumanDecisionsError = ListHumanDecisionsErrors[keyof ListHumanDecisionsErrors];

export type ListHumanDecisionsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: DecisionPage;
};

export type ListHumanDecisionsResponse = ListHumanDecisionsResponses[keyof ListHumanDecisionsResponses];

export type RecordHumanDecisionData = {
    body: DecisionCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/findings/{id}/decisions';
};

export type RecordHumanDecisionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RecordHumanDecisionError = RecordHumanDecisionErrors[keyof RecordHumanDecisionErrors];

export type RecordHumanDecisionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RecordHumanDecisionResponse = RecordHumanDecisionResponses[keyof RecordHumanDecisionResponses];

export type RequestAgentExecutionData = {
    body: AgentExecutionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/agent-executions';
};

export type RequestAgentExecutionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RequestAgentExecutionError = RequestAgentExecutionErrors[keyof RequestAgentExecutionErrors];

export type RequestAgentExecutionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    202: WorkResult;
};

export type RequestAgentExecutionResponse = RequestAgentExecutionResponses[keyof RequestAgentExecutionResponses];

export type GetAgentExecutionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/agent-executions/{id}';
};

export type GetAgentExecutionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetAgentExecutionError = GetAgentExecutionErrors[keyof GetAgentExecutionErrors];

export type GetAgentExecutionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: AgentExecution;
};

export type GetAgentExecutionResponse = GetAgentExecutionResponses[keyof GetAgentExecutionResponses];

export type CancelAgentExecutionData = {
    body: CancelAgentExecution;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/agent-executions/{id}/cancel';
};

export type CancelAgentExecutionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type CancelAgentExecutionError = CancelAgentExecutionErrors[keyof CancelAgentExecutionErrors];

export type CancelAgentExecutionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type CancelAgentExecutionResponse = CancelAgentExecutionResponses[keyof CancelAgentExecutionResponses];

export type GetAgentResultData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/agent-executions/{id}/result';
};

export type GetAgentResultErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type GetAgentResultError = GetAgentResultErrors[keyof GetAgentResultErrors];

export type GetAgentResultResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: AgentResult;
};

export type GetAgentResultResponse = GetAgentResultResponses[keyof GetAgentResultResponses];

export type ExecuteOrganizationWorkflowActionData = {
    body: WorkflowActionCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/actions';
};

export type ExecuteOrganizationWorkflowActionErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ExecuteOrganizationWorkflowActionError = ExecuteOrganizationWorkflowActionErrors[keyof ExecuteOrganizationWorkflowActionErrors];

export type ExecuteOrganizationWorkflowActionResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type ExecuteOrganizationWorkflowActionResponse = ExecuteOrganizationWorkflowActionResponses[keyof ExecuteOrganizationWorkflowActionResponses];

export type ListOrganizationalUnitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organization/units';
};

export type ListOrganizationalUnitsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListOrganizationalUnitsError = ListOrganizationalUnitsErrors[keyof ListOrganizationalUnitsErrors];

export type ListOrganizationalUnitsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: UnitPage;
};

export type ListOrganizationalUnitsResponse = ListOrganizationalUnitsResponses[keyof ListOrganizationalUnitsResponses];

export type ListBusinessRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organization/roles';
};

export type ListBusinessRolesErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListBusinessRolesError = ListBusinessRolesErrors[keyof ListBusinessRolesErrors];

export type ListBusinessRolesResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: RolePage;
};

export type ListBusinessRolesResponse = ListBusinessRolesResponses[keyof ListBusinessRolesResponses];

export type ListRoleAssignmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organization/role-assignments';
};

export type ListRoleAssignmentsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListRoleAssignmentsError = ListRoleAssignmentsErrors[keyof ListRoleAssignmentsErrors];

export type ListRoleAssignmentsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: RoleAssignmentPage;
};

export type ListRoleAssignmentsResponse = ListRoleAssignmentsResponses[keyof ListRoleAssignmentsResponses];

export type CreateRoleAssignmentData = {
    body: RoleAssignmentCommand;
    path?: never;
    query?: never;
    url: '/v1/organization/role-assignments';
};

export type CreateRoleAssignmentErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type CreateRoleAssignmentError = CreateRoleAssignmentErrors[keyof CreateRoleAssignmentErrors];

export type CreateRoleAssignmentResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type CreateRoleAssignmentResponse = CreateRoleAssignmentResponses[keyof CreateRoleAssignmentResponses];

export type RevokeRoleAssignmentData = {
    body: RevokePolicyRecordCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/role-assignments/{id}/revoke';
};

export type RevokeRoleAssignmentErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RevokeRoleAssignmentError = RevokeRoleAssignmentErrors[keyof RevokeRoleAssignmentErrors];

export type RevokeRoleAssignmentResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RevokeRoleAssignmentResponse = RevokeRoleAssignmentResponses[keyof RevokeRoleAssignmentResponses];

export type ListDelegationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/organization/delegations';
};

export type ListDelegationsErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type ListDelegationsError = ListDelegationsErrors[keyof ListDelegationsErrors];

export type ListDelegationsResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: DelegationPage;
};

export type ListDelegationsResponse = ListDelegationsResponses[keyof ListDelegationsResponses];

export type CreateDelegationData = {
    body: DelegationCommand;
    path?: never;
    query?: never;
    url: '/v1/organization/delegations';
};

export type CreateDelegationErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type CreateDelegationError = CreateDelegationErrors[keyof CreateDelegationErrors];

export type CreateDelegationResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type CreateDelegationResponse = CreateDelegationResponses[keyof CreateDelegationResponses];

export type RevokeDelegationData = {
    body: RevokePolicyRecordCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/delegations/{id}/revoke';
};

export type RevokeDelegationErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type RevokeDelegationError = RevokeDelegationErrors[keyof RevokeDelegationErrors];

export type RevokeDelegationResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type RevokeDelegationResponse = RevokeDelegationResponses[keyof RevokeDelegationResponses];

export type AssignWorkItemData = {
    body: AssignmentCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/organization/tasks/{id}/assignment';
};

export type AssignWorkItemErrors = {
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    422: Problem;
    /**
     * 安全なRFC9457エラー。外部状態不明を成功としない
     */
    default: Problem;
};

export type AssignWorkItemError = AssignWorkItemErrors[keyof AssignWorkItemErrors];

export type AssignWorkItemResponses = {
    /**
     * 現在の認可で評価した結果
     */
    200: WorkResult;
};

export type AssignWorkItemResponse = AssignWorkItemResponses[keyof AssignWorkItemResponses];
