[package]
name = "search-application"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
search-core = { version = "0.0.0", path = "../search-core" }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
time.workspace = true
tokio.workspace = true
uuid.workspace = true
