[package]
name = "work-repository-postgres"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
work-domain = { path = "../work-domain", version = "0.0.0" }
work-application = { path = "../work-application", version = "0.0.0" }
serde_json.workspace = true
sqlx.workspace = true
sha2.workspace = true
uuid.workspace = true
time = { workspace = true, features = ["formatting"] }

tokio.workspace = true
