import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
const {runQualification}=await import('../controller.mjs').catch(()=>({}));
const plan=()=>({stage:'small',documentCount:2,fingerprint:{code:'code',corpus:'corpus',runtime:'runtime'},safetyFactor:2,budgets:{diskReserveBytes:100,minAvailableMemoryBytes:100,maxRssBytes:1000,maxWallTimeMs:30000},deadlineAt:new Date(Date.now()+30000).toISOString()});
const observation=()=>({observedAt:new Date().toISOString(),diskFreeBytes:10000,storageDiskFreeBytes:20000,databaseDiskFreeBytes:10000,availableMemoryBytes:10000,rssBytes:500,rssCoverage:'process-tree',databaseFilesystemVerified:true,storageBytes:0,databaseBytes:100,limitations:[]});
test('no metrics means NOT_ADMITTED and no mutation, never success',async t=>{assert.equal(typeof runQualification,'function');const dir=await mkdtemp(join(tmpdir(),'controller-'));t.after(()=>rm(dir,{recursive:true,force:true}));let mutation=false;const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>({...observation(),rssBytes:null})},probeFactory:()=>{mutation=true;},execute:async()=>{mutation=true;}});assert.equal(report.status,'NOT_ADMITTED');assert.equal(mutation,false);assert.equal(JSON.parse(await readFile(join(dir,'report.json'))).status,'NOT_ADMITTED');});
test('restart requires changed server processes and unchanged owned dataset',async t=>{assert.equal(typeof runQualification,'function');const dir=await mkdtemp(join(tmpdir(),'controller-'));t.after(()=>rm(dir,{recursive:true,force:true}));const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:100,agentPid:200}),restart:async()=>{}},probeFactory:()=>({}),execute:async()=>({status:'AWAITING_RESTART'}),verify:async()=>({status:'SUCCEEDED'})});assert.equal(report.status,'FAILED');assert.equal(report.failureCode,'restart-proof-failed');});
test('successful controller reports only observed metrics with paired restart evidence',async t=>{assert.equal(typeof runQualification,'function');const dir=await mkdtemp(join(tmpdir(),'controller-'));t.after(()=>rm(dir,{recursive:true,force:true}));let restart=false;const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:restart?101:100,agentPid:restart?201:200}),restart:async()=>{restart=true;}},probeFactory:()=>({}),execute:async()=>({status:'AWAITING_RESTART'}),verify:async()=>({status:'SUCCEEDED'})});assert.equal(report.status,'SUCCEEDED');assert.equal(report.metrics.peakRssBytes,500);assert.equal(report.metrics.diskGrowthBytes,0);assert.ok(report.metrics.totalElapsedMs>0);assert.equal(report.productionSloClaim,false);});
test('resource aggregation handles 250,000 samples without variadic stack overflow',async()=>{const {summarizeResources}=await import('../controller.mjs');assert.equal(typeof summarizeResources,'function');const values=Array.from({length:250000},(_,i)=>({rssBytes:i+1,diskFreeBytes:1000000-i,storageDiskFreeBytes:1000000-i,databaseDiskFreeBytes:1000000,databaseBytes:100+i,storageBytes:i}));const summary=summarizeResources(values,100);assert.equal(summary.peakRssBytes,250000);assert.equal(summary.diskGrowthBytes,499998);});
test('wall budget expiring during final observation cannot publish success',async t=>{const dir=await mkdtemp(join(tmpdir(),'controller-deadline-'));t.after(()=>rm(dir,{recursive:true,force:true}));let restarted=false;const p=plan();p.budgets.maxWallTimeMs=30;const report=await runQualification({directory:dir,runId:'test',plan:p,corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>{if(restarted)await new Promise(r=>setTimeout(r,80));return observation();},identity:async()=>({dataset:'same',humanPid:restarted?101:100,agentPid:restarted?201:200}),restart:async()=>{restarted=true;}},probeFactory:()=>({}),execute:async()=>({status:'AWAITING_RESTART'}),verify:async()=>({status:'SUCCEEDED'})});assert.equal(report.status,'ABORTED');assert.equal(report.failureCode,'wall-budget-exhausted');});

test('storage growth cannot be hidden by a smaller unchanged database filesystem',async()=>{const {summarizeResources}=await import('../controller.mjs');const before={rssBytes:10,diskFreeBytes:1000,storageDiskFreeBytes:10000,databaseDiskFreeBytes:1000,storageBytes:0,databaseBytes:100};const after={...before,storageDiskFreeBytes:9000,storageBytes:900};assert.equal(summarizeResources([before,after],10).diskGrowthBytes,1000);});
test('failed first publish reports actual counts and bounded DSI diagnostics without qualifying partial metrics',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'controller-publish-'));t.after(()=>rm(dir,{recursive:true,force:true}));const fileId='0198eada-1234-7000-8000-000000000001';let diagnostics=0;
 const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:100,agentPid:200}),diagnosePublication:async id=>{assert.equal(id,fileId);diagnostics++;return{rowCount:1,pdf:true,rawHashMatches:true,sizeMatches:true,unresolvedTrackedChanges:0,embeddedComments:2,invalidSignatures:0,unverifiableSignatures:0,diagnosticCount:0,content:'PRIVATE_SENTINEL'};}},probeFactory:()=>({}),execute:async({journal})=>{
  await journal.perform('create:0',{},async()=>({documentId:'doc',documentVersionId:'version',fileId}),{recoverable:false});
  await journal.perform('publish:0',{},async()=>{const error=Error('PRIVATE_SENTINEL');error.diagnostic={operation:'publish',httpStatus:422,problemCode:'PUBLISH_QUALITY_REJECTED',detail:'PRIVATE_SENTINEL'};throw error;});
 }});
 assert.equal(report.status,'FAILED');assert.deepEqual(report.counts,{targetDocuments:2,confirmedCreatedDocuments:1,confirmedPublishedDocuments:0});assert.equal(report.metricQualification,'partial-failed-stage');assert.equal(diagnostics,1);assert.equal(report.failureDiagnostic.problemCode,'PUBLISH_QUALITY_REJECTED');assert.equal(report.inspectionDiagnostic.embeddedComments,2);assert.ok(!JSON.stringify(report).includes('PRIVATE_SENTINEL'));
});
test('missing DSI on BUSINESS_RULE_REJECTED invokes only a bound worker diagnosis and preserves FAILED',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'controller-worker-'));t.after(()=>rm(dir,{recursive:true,force:true}));const fileId='0198eada-1234-7000-8000-000000000001';let calls=0;
 const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:100,agentPid:200}),diagnosePublication:async()=>({rowCount:0}),diagnoseWorker:async(id,binding)=>{assert.equal(id,fileId);assert.deepEqual(binding,{assetId:'official-a',sha256:'a'.repeat(64)});calls++;return{status:'worker-failure',failureCode:'unsupported_semantic_construct',message:'PRIVATE_SENTINEL'};}},probeFactory:()=>({}),execute:async({journal})=>{
  await journal.perform('create:0',{assetId:'official-a',sha256:'a'.repeat(64)},async()=>({documentId:'doc',documentVersionId:'version',fileId}),{recoverable:false});
  await journal.perform('publish:0',{},async()=>{const error=Error('PRIVATE_SENTINEL');error.diagnostic={operation:'publish',httpStatus:422,problemCode:'BUSINESS_RULE_REJECTED'};throw error;});
 }});
 assert.equal(calls,1);assert.equal(report.status,'FAILED');assert.equal(report.workerDiagnostic.failureCode,'unsupported_semantic_construct');assert.equal(report.workerDiagnostic.qualification,false);assert.ok(!JSON.stringify(report).includes('PRIVATE_SENTINEL'));
});

test('negative corpus must be verified before positive workload and after the same real restart',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'controller-negative-'));t.after(()=>rm(dir,{recursive:true,force:true}));let restarted=false;const calls=[];const negative={status:'AWAITING_RESTART',counts:{confirmedRejectedDocuments:1}};
 const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[],negativeAssets:[{id:'negative'}]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:restarted?101:100,agentPid:restarted?201:200}),restart:async()=>{calls.push('restart');restarted=true;},diagnosePublication:async()=>{},diagnoseWorker:async()=>{}},probeFactory:()=>({}),executeNegative:async options=>{assert.equal(options.stageLabel,'small');assert.equal(options.assets[0].id,'negative');assert.equal(typeof options.diagnoseWorker,'function');calls.push('negative');return negative;},execute:async options=>{assert.equal(options.stageLabel,'small');calls.push('positive');return{};},verify:async()=>{calls.push('positive-retained');},verifyNegative:async options=>{assert.equal(options.evidence,negative);calls.push('negative-retained');return{status:'SUCCEEDED'};}});
 assert.equal(report.status,'SUCCEEDED');assert.deepEqual(calls,['negative','positive','restart','positive-retained','negative-retained']);assert.equal(report.negativeCorpus.status,'SUCCEEDED');
});
test('failed negative restart retention cannot qualify the positive stage',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'controller-negative-fail-'));t.after(()=>rm(dir,{recursive:true,force:true}));let restarted=false;
 const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[],negativeAssets:[{}]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:restarted?101:100,agentPid:restarted?201:200}),restart:async()=>{restarted=true;}},probeFactory:()=>({}),executeNegative:async()=>({status:'AWAITING_RESTART'}),execute:async()=>({}),verify:async()=>{},verifyNegative:async()=>{throw Error('PRIVATE_SENTINEL');}});
 assert.equal(report.status,'FAILED');assert.ok(!JSON.stringify(report).includes('PRIVATE_SENTINEL'));
});
test('negative diagnostic failure preserves confirmed create and known HTTP422 counts',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'controller-negative-count-'));t.after(()=>rm(dir,{recursive:true,force:true}));
 const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[],negativeAssets:[{}]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:100,agentPid:200})},probeFactory:()=>({}),executeNegative:async({journal})=>{await journal.perform('negative-create:0',{},async()=>({documentId:'owned'}),{recoverable:false});await journal.perform('negative-publish:0',{},async()=>({outcome:'rejected-unsupported',failureDiagnostic:{operation:'publish',httpStatus:422,problemCode:'BUSINESS_RULE_REJECTED'}}));throw Error('PRIVATE_SENTINEL');}});
 assert.equal(report.status,'FAILED');assert.deepEqual(report.negativeCorpus.counts,{targetDocuments:1,confirmedCreatedDocuments:1,confirmedHttp422Responses:1,confirmedRejectedDocuments:0,confirmedPublishedDocuments:0});assert.equal(report.negativeCorpus.status,'FAILED');assert.ok(!JSON.stringify(report).includes('PRIVATE_SENTINEL'));
});
test('known unexpected negative publication remains counted as a failed qualification',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'controller-negative-success-'));t.after(()=>rm(dir,{recursive:true,force:true}));
 const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[],negativeAssets:[{}]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:100,agentPid:200})},probeFactory:()=>({}),executeNegative:async({journal})=>{await journal.perform('negative-create:0',{},async()=>({documentId:'owned'}),{recoverable:false});await journal.perform('negative-publish:0',{},async()=>({outcome:'unexpected-published'}));throw Error('PRIVATE_SENTINEL');}});
 assert.equal(report.status,'FAILED');assert.equal(report.negativeCorpus.counts.confirmedPublishedDocuments,1);assert.equal(report.negativeCorpus.counts.confirmedRejectedDocuments,0);
});
