import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
const {runQualification}=await import('../controller.mjs').catch(()=>({}));
const plan=()=>({stage:'small',documentCount:2,fingerprint:{code:'code',corpus:'corpus',runtime:'runtime'},safetyFactor:2,budgets:{diskReserveBytes:100,minAvailableMemoryBytes:100,maxRssBytes:1000,maxWallTimeMs:30000},deadlineAt:new Date(Date.now()+30000).toISOString()});
const observation=()=>({observedAt:new Date().toISOString(),diskFreeBytes:10000,storageDiskFreeBytes:20000,databaseDiskFreeBytes:10000,availableMemoryBytes:10000,rssBytes:500,rssCoverage:'process-tree',databaseFilesystemVerified:true,storageBytes:0,databaseBytes:100,limitations:[]});
test('no metrics means NOT_ADMITTED and no mutation, never success',async t=>{assert.equal(typeof runQualification,'function');const dir=await mkdtemp(join(tmpdir(),'controller-'));t.after(()=>rm(dir,{recursive:true,force:true}));let mutation=false;const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>({...observation(),rssBytes:null})},probeFactory:()=>{mutation=true;},execute:async()=>{mutation=true;}});assert.equal(report.status,'NOT_ADMITTED');assert.equal(mutation,false);assert.equal(JSON.parse(await readFile(join(dir,'report.json'))).status,'NOT_ADMITTED');});
test('restart requires changed server processes and unchanged owned dataset',async t=>{assert.equal(typeof runQualification,'function');const dir=await mkdtemp(join(tmpdir(),'controller-'));t.after(()=>rm(dir,{recursive:true,force:true}));const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:100,agentPid:200}),restart:async()=>{}},probeFactory:()=>({}),execute:async()=>({status:'AWAITING_RESTART'}),verify:async()=>({status:'SUCCEEDED'})});assert.equal(report.status,'FAILED');assert.equal(report.failureCode,'restart-proof-failed');});
test('successful controller reports only observed metrics with paired restart evidence',async t=>{assert.equal(typeof runQualification,'function');const dir=await mkdtemp(join(tmpdir(),'controller-'));t.after(()=>rm(dir,{recursive:true,force:true}));let restart=false;const report=await runQualification({directory:dir,runId:'test',plan:plan(),corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>observation(),identity:async()=>({dataset:'same',humanPid:restart?101:100,agentPid:restart?201:200}),restart:async()=>{restart=true;}},probeFactory:()=>({}),execute:async()=>({status:'AWAITING_RESTART'}),verify:async()=>({status:'SUCCEEDED'})});assert.equal(report.status,'SUCCEEDED');assert.equal(report.metrics.peakRssBytes,500);assert.equal(report.metrics.diskGrowthBytes,0);assert.ok(report.metrics.totalElapsedMs>0);assert.equal(report.productionSloClaim,false);});
test('resource aggregation handles 250,000 samples without variadic stack overflow',async()=>{const {summarizeResources}=await import('../controller.mjs');assert.equal(typeof summarizeResources,'function');const values=Array.from({length:250000},(_,i)=>({rssBytes:i+1,diskFreeBytes:1000000-i,storageDiskFreeBytes:1000000-i,databaseDiskFreeBytes:1000000,databaseBytes:100+i,storageBytes:i}));const summary=summarizeResources(values,100);assert.equal(summary.peakRssBytes,250000);assert.equal(summary.diskGrowthBytes,499998);});
test('wall budget expiring during final observation cannot publish success',async t=>{const dir=await mkdtemp(join(tmpdir(),'controller-deadline-'));t.after(()=>rm(dir,{recursive:true,force:true}));let restarted=false;const p=plan();p.budgets.maxWallTimeMs=30;const report=await runQualification({directory:dir,runId:'test',plan:p,corpus:{hash:'corpus',assets:[]},runtime:{observe:async()=>{if(restarted)await new Promise(r=>setTimeout(r,80));return observation();},identity:async()=>({dataset:'same',humanPid:restarted?101:100,agentPid:restarted?201:200}),restart:async()=>{restarted=true;}},probeFactory:()=>({}),execute:async()=>({status:'AWAITING_RESTART'}),verify:async()=>({status:'SUCCEEDED'})});assert.equal(report.status,'ABORTED');assert.equal(report.failureCode,'wall-budget-exhausted');});

test('storage growth cannot be hidden by a smaller unchanged database filesystem',async()=>{const {summarizeResources}=await import('../controller.mjs');const before={rssBytes:10,diskFreeBytes:1000,storageDiskFreeBytes:10000,databaseDiskFreeBytes:1000,storageBytes:0,databaseBytes:100};const after={...before,storageDiskFreeBytes:9000,storageBytes:900};assert.equal(summarizeResources([before,after],10).diskGrowthBytes,1000);});
