import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile, appendFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const module = await import('../journal.mjs').catch(() => ({}));
const Journal = module.Journal;
async function setup(t) { const dir=await mkdtemp(join(tmpdir(),'document-load-journal-')); t.after(()=>rm(dir,{recursive:true,force:true})); return join(dir,'journal.jsonl'); }
test('journal is provided as a durable operation boundary',()=>assert.equal(typeof Journal,'function'));
test('completed operation reopens without repeating mutation and rejects drift',async t=>{ if(!Journal) return assert.fail('Journal absent'); const path=await setup(t); let j=await Journal.open(path,{run:'a'}); let calls=0; assert.deepEqual(await j.perform('create:0',{hash:'a'},async()=>{calls++;return {id:1};},{recoverable:false}),{id:1}); await j.close(); j=await Journal.open(path,{run:'a'}); assert.deepEqual(await j.perform('create:0',{hash:'a'},async()=>{calls++;},{recoverable:false}),{id:1}); assert.equal(calls,1); await assert.rejects(j.perform('create:0',{hash:'b'},async()=>{}),/drift/); await j.close(); });
test('unknown initial create refuses replay after reopen',async t=>{ if(!Journal)return assert.fail('Journal absent');const path=await setup(t);let j=await Journal.open(path,{run:'a'});await assert.rejects(j.perform('create:0',{},async()=>{throw Error('lost response');},{recoverable:false}),/lost/);await j.close();j=await Journal.open(path,{run:'a'});await assert.rejects(j.perform('create:0',{},async()=>assert.fail('duplicate create'),{recoverable:false}),/unknown/);await j.close();});
test('recoverable mutation replays exact persisted request',async t=>{if(!Journal)return assert.fail('Journal absent');const path=await setup(t);let j=await Journal.open(path,{run:'a'});const request={operationId:'fixed',expectedRevision:1};await assert.rejects(j.perform('publish:0',request,async()=>{throw Error('lost');}));await j.close();j=await Journal.open(path,{run:'a'});assert.deepEqual(await j.perform('publish:0',request,async received=>received),request);await j.close();});
test('identity drift, concurrent writer and truncated tail fail closed',async t=>{if(!Journal)return assert.fail('Journal absent');const path=await setup(t);let j=await Journal.open(path,{run:'a'});await assert.rejects(Journal.open(path,{run:'a'}),/lock/);await j.close();await assert.rejects(Journal.open(path,{run:'b'}),/identity/);await appendFile(path,'{"incomplete"');await assert.rejects(Journal.open(path,{run:'a'}),/truncated/);});
test('journal rejects a hash-valid file missing its identity header',async t=>{const path=await setup(t);const {createHash}=await import('node:crypto');const canonical=value=>JSON.stringify(value,(_,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item);const record={kind:'pending',key:'create:0',request:{},recoverable:false,sequence:0,previous:null};const hash=createHash('sha256').update(canonical(record)).digest('hex');await appendFile(path,JSON.stringify({...record,hash})+'\n');await assert.rejects(Journal.open(path,{run:'a'}),/identity/);});
