import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';
const source=()=>readFile(new URL('../../../.github/workflows/document-load-thousand.yml',import.meta.url),'utf8');
test('long run is manual-only, main-only, same public repository and fixed1000 target',async()=>{
 const y=await source();const events=y.split('permissions:')[0];assert.match(events,/workflow_dispatch:/);assert.doesNotMatch(events,/(?:push|pull_request|schedule)\s*:/);assert.match(events,/options: \['1000'\]/);assert.match(y,/github\.repository == 'AIrisu-072\/knowledge-platform'/);assert.match(y,/github\.ref == 'refs\/heads\/main'/);assert.match(y,/github\.event\.repository\.private == false/);assert.match(y,/inputs\.stage == '1000'/);assert.match(y,/runs-on: ubuntu-24.04/);assert.match(y,/timeout-minutes: 180/);assert.match(y,/cancel-in-progress: false/);assert.match(y,/contents: read/);assert.doesNotMatch(y,/write-all|contents: write|secrets\./);
});
test('long run reuses pinned build and mandatory owned runtime, with success-only single safe receipt',async()=>{
 const y=await source();assert.match(y,/persist-credentials: false/);assert.match(y,/ref: \$\{\{ github.sha \}\}/);assert.match(y,/pnpm install --frozen-lockfile --ignore-scripts/);assert.match(y,/pnpm --dir tools\/document-load-qualification test/);assert.match(y,/export KP_DOCUMENT_LOAD_THOUSAND=true/);assert.match(y,/unset KP_DOCUMENT_LOAD_SMALL KP_DOCUMENT_LOAD_PLAN/);assert.match(y,/mise run document:poc:agent/);assert.doesNotMatch(y,/--prebuilt|TEST_DATABASE_URL|KP_DOCUMENT_LOAD_PLAN=/);assert.match(y,/if: \$\{\{ success\(\) \}\}/);assert.match(y,/retention-days: 1/);assert.match(y,/path: tools\/document-poc-runtime\/\.state\/document-load-export\/qualification\.json/);assert.match(y,/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a/);assert.doesNotMatch(y,/10000|100000|path:.*\*/);
});
test('normal Document CI keeps45 minutes and cannot inherit1000 mode',async()=>{
 const y=await readFile(new URL('../../../.github/workflows/ci.yml',import.meta.url),'utf8');const job=y.split('  document-poc-runtime:')[1].split('\n  document-mcp:')[0];assert.match(job,/timeout-minutes: 45/);assert.match(job,/unset KP_DOCUMENT_LOAD_SMALL KP_DOCUMENT_LOAD_PLAN KP_DOCUMENT_LOAD_THOUSAND/);assert.doesNotMatch(job,/export KP_DOCUMENT_LOAD_THOUSAND=true/);
});
