import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{Journal}from'../journal.mjs';
const {exerciseStage,verifyRetained}=await import('../workflow.mjs').catch(()=>({}));
function fake(){let seq=0;const docs=new Map();return {docs,verifySessions:async()=>({rootFolderId:'root',root:{revision:0}}),createFolder:async req=>({folderId:req.folderId}),setFolderPolicy:async()=>({revision:1}),create:async asset=>{const id=`doc${++seq}`,v=`v${seq}`;docs.set(id,{documentId:id,folderId:asset.folderId,currentVersionId:null,revision:0,metadata:{},versions:[v],hashes:{[v]:asset.bytes.toString()},private:false});return {documentId:id,documentVersionId:v,fileId:`f${seq}`};},detail:async id=>structuredClone(docs.get(id)),publish:async(id,v)=>{const d=docs.get(id);d.currentVersionId=v;d.revision++;return {currentVersionId:v};},list:async(folder,who)=>[...docs.values()].filter(d=>d.folderId===folder&&!(who==='agent'&&d.private)).map(d=>d.documentId),updateMetadata:async(id,rev,op)=>{const d=docs.get(id);if(rev!==d.revision){const e=Error('OCC');e.status=409;throw e;}d.metadata={extensions:{loadQualificationOperation:op}};d.revision++;return {revision:d.revision};},createNextVersion:async(id,rev,op,v,file,asset)=>{docs.get(id).versions.push(v);docs.get(id).hashes[v]=asset.bytes.toString();return{versionId:v};},snapshot:async id=>{const d=docs.get(id);return {detail:structuredClone(d),policy:{policyRevision:d.private?1:0},versions:d.versions.map(versionId=>({summary:{versionId},files:[{sha256:d.hashes[versionId]}]}))};},denyAgent:async id=>{docs.get(id).private=true;return {policyRevision:1};},agentReadStatus:async id=>({status:docs.get(id).private?404:200,allowed:!docs.get(id).private})};}
async function context(t){const dir=await mkdtemp(join(tmpdir(),'load-workflow-'));const journal=await Journal.open(join(dir,'journal'),{run:'test'});t.after(async()=>{await journal.close();await rm(dir,{recursive:true,force:true});});return {journal,probe:fake(),count:3,assets:[{id:'a',bytes:Buffer.from('a'),sha256:'a',filename:'a.pdf',mediaType:'application/pdf'},{id:'b',bytes:Buffer.from('b'),sha256:'b',filename:'b.pdf',mediaType:'application/pdf'}],checkpoint:async()=>{},runId:'test'};}
test('stage exercises real-contract operations and leaves restart verification pending',async t=>{assert.equal(typeof exerciseStage,'function');const c=await context(t);const result=await exerciseStage(c);assert.equal(result.status,'AWAITING_RESTART');assert.equal(result.documentIds.length,3);assert.equal(result.privateDocumentId,result.documentIds[2]);assert.equal(result.sampledDocumentIds.length,3);await verifyRetained({...c,evidence:result});});
test('missing list entry cannot qualify stage and checkpoint failure prevents creates',async t=>{assert.equal(typeof exerciseStage,'function');const c=await context(t);c.probe.list=async()=>[];await assert.rejects(exerciseStage(c),/list/);const d=await context(t);d.checkpoint=async()=>{throw Error('capacity stop');};await assert.rejects(exerciseStage(d),/capacity/);assert.equal(d.probe.docs.size,0);});
test('restart detects changed retained state and leaked private list membership',async t=>{assert.equal(typeof exerciseStage,'function');const c=await context(t);const evidence=await exerciseStage(c);c.probe.docs.get(evidence.documentIds[0]).revision++;await assert.rejects(verifyRetained({...c,evidence}),/retained/);});
test('different source labels with identical original bytes do not qualify content switching',async t=>{const c=await context(t);c.assets[1].sha256=c.assets[0].sha256;await assert.rejects(exerciseStage(c),/distinct/);assert.equal(c.probe.docs.size,0);});
test('co-located stages use distinct fixed folder names without changing the run UUID',async t=>{
 const names=[];
 for(const stageLabel of ['small',1000]){
  const c=await context(t);c.stageLabel=stageLabel;c.probe.createFolder=async req=>{names.push(req.name);return{folderId:req.folderId};};await exerciseStage(c);
 }
 assert.equal(new Set(names.map(n=>n.toLowerCase())).size,2);assert.ok(names.every(n=>n.includes('test')));
});
